BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "dormir" ( id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, afirmaciones TEXT NOT NULL );
CREATE TABLE IF NOT EXISTS "manana" ( id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, afirmaciones TEXT NOT NULL );
CREATE TABLE IF NOT EXISTS "riqueza" ( id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, afirmaciones TEXT NOT NULL );
CREATE TABLE IF NOT EXISTS "louisehay" (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,afirmaciones TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "amorpropio" (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,afirmaciones TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "amor" (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,afirmaciones TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "atencion" (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,afirmaciones TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "mente" (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,afirmaciones TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "negocio" (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,afirmaciones TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS "salud" (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,afirmaciones TEXT NOT NULL);
INSERT INTO "amor" ("afirmaciones") VALUES ('Solo atraigo personas confiables y positivas.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Doy y recibo amor por igual.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Abro mi corazón al amor y a la vida.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Tengo abundancia de amor para dar.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Cuanto más me amo más amor siento por los demás.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Expreso mis deseos y necesidades de manera clara y asertiva.');
INSERT INTO "amor" ("afirmaciones") VALUES ('El amor trae energía y alegría a mi vida.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Mis relaciones están llenas de respeto, comprensión y amor.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Soy una persona valiosa y me amo.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Tengo lazos cercanos y saludables con mi pareja.');
INSERT INTO "amor" ("afirmaciones") VALUES ('En mis relaciones hay amor y comprensión.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Amo incondicionalmente y sin dudarlo.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Amo con aceptación y libertad.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Vibro en la frecuencia del amor más auténtico.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Todas mis relaciones son armoniosas.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Donde quiera que voy, estoy acompañado de amor.');
INSERT INTO "amor" ("afirmaciones") VALUES ('El amor verdadero llega a mi vida para quedarse.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Mi matrimonio (o relación) es más fuerte, más profunda y más amorosa cada día.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Mantengo relaciones saludables y plenas con mi pareja y amigos.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Doy gracias a la vida por darme la capacidad de amar y ser amada.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Mi vida es maravillosa, amo a mi familia y ellos me aman a mí.');
INSERT INTO "amor" ("afirmaciones") VALUES ('Doy gracias a la vida por darme la capacidad de amar y ser amado');
INSERT INTO "amor" ("afirmaciones") VALUES ('El amor de mi vida está viniendo hacia mí en este momento');
INSERT INTO "amor" ("afirmaciones") VALUES ('El amor de mi corazón inunda alegremente todo mi cuerpo');
INSERT INTO "amor" ("afirmaciones") VALUES ('Me amo y disfruto conmigo misma');
INSERT INTO "amor" ("afirmaciones") VALUES ('Mi corazón está abierto.  Estoy dispuesta a abandonar toda resistencia');
INSERT INTO "amor" ("afirmaciones") VALUES ('Me amo a mi mismo exactamente como soy ahora mismo');
INSERT INTO "amor" ("afirmaciones") VALUES ('Desarrollo conexiones profundas con quienes me rodean');
INSERT INTO "amor" ("afirmaciones") VALUES ('Mi luz interior atrae amor');
INSERT INTO "amor" ("afirmaciones") VALUES ('Me siento a gusto con todas las personas que conozco. Todas mis relaciones son sanas y alentadoras');
INSERT INTO "amor" ("afirmaciones") VALUES ('Merezco disfrutar la vida. Pido lo que merezco y lo acepto con placer y alegría');
INSERT INTO "amor" ("afirmaciones") VALUES ('Mi vida está llena de amor');
INSERT INTO "amor" ("afirmaciones") VALUES ('Tengo abundancia de amor para dar');
INSERT INTO "amor" ("afirmaciones") VALUES ('Atraigo todo romanticismo a mi vida');
INSERT INTO "amor" ("afirmaciones") VALUES ('Permito que el amor me encuentre. Estoy determinado a atraerlo hacia mí');
INSERT INTO "amor" ("afirmaciones") VALUES ('Respiro amor, siento amor');
INSERT INTO "amor" ("afirmaciones") VALUES ('Te observo claramente con los ojos del amor y me encanta lo que veo');
INSERT INTO "amor" ("afirmaciones") VALUES ('Doy y recibo amor con pasión y ternura');
INSERT INTO "amor" ("afirmaciones") VALUES ('El amor lo puede todo');
INSERT INTO "amor" ("afirmaciones") VALUES ('Soy merecedor de tener a mi lado al amor de mi vida');
INSERT INTO "amor" ("afirmaciones") VALUES ('Estoy en proceso de atraer hacia mí a mi alma gemela');
INSERT INTO "amor" ("afirmaciones") VALUES ('Doy gracias al destino por ser capaz de amar y ser amado incondicionalmente');
INSERT INTO "amor" ("afirmaciones") VALUES ('A quién busco, también me busca a mí, estamos unidos por el infinito');
INSERT INTO "amor" ("afirmaciones") VALUES ('Abro las puertas a un amor sano y verdadero');
INSERT INTO "amor" ("afirmaciones") VALUES ('Siento inmensa gratitud por tener a mi compañero/a ideal a mi lado');
INSERT INTO "amor" ("afirmaciones") VALUES ('Yo merezco amor, romance, felicidad, y todo lo bueno que la vida tiene para ofrecerme');
INSERT INTO "amor" ("afirmaciones") VALUES ('Tengo una pareja que me ama y me acepta tal como soy');
INSERT INTO "amor" ("afirmaciones") VALUES ('Sé reconocer a la persona indicada para establecer la relación que quiero');
INSERT INTO "amor" ("afirmaciones") VALUES ('El amor llega a mi vida trayendo inmensas satisfacciones');
INSERT INTO "amor" ("afirmaciones") VALUES ('Agradezco las relaciones que he tenido porque me han preparado para este momento perfecto');
INSERT INTO "amor" ("afirmaciones") VALUES ('Soy libre cuando estoy solo/a y cuando estoy en pareja');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Todo lo que busco lo encuentro dentro de mí.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Merezco amar y ser amada.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me acepto y me amo incondicionalmente.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('El amor propio es mi prioridad intencional.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Amo el cuerpo que mi alma ha elegido para habitar y vivir.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Estoy dispuesta a cuidar mi cuerpo, mi alma, mi mente y mis emociones.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Irradio confianza.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Soy mi lugar seguro y lleno de amor.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Decido darme lo mejor y apreciarme más cada día.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Acepto y reconozco la divinidad en mí.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Practico el autocuidado personal y me amo.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Soy merecedora de todo lo bueno que la vida me puede ofrecer.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Tengo el poder de co-crear la vida que amo.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me siento cómoda en mi cuerpo.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('El amor fluye a través de mí.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Creo y confío en mí.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Amo mi cuerpo y lo respeto.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Mi cuerpo es mi mejor amigo.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Envío amor y salud a cada parte de mi cuerpo.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Soy única, maravillosa y auténtica.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Mi vida y mi felicidad son importantes.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Entiendo que mis sueños y aspiraciones son mi responsabilidad.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Avanzo con la frente en alto, feliz de ser quien soy.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me siento orgullosa de la persona que veo al mirarme al espejo.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Confío en mi intuición y respeto mi voz interior.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Amo cada parte de mí.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Añado valor al mundo y tengo un propósito maravilloso.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Escucho y respeto mi cuerpo y disfruto de buena salud.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me acepto y me amo tal como soy mientras trabajo en mi desarrollo continuo y cuidado personal.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Aprecio el sinérgico trabajo que cada parte de mi cuerpo realiza día tras día.');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Merezco lo mejor y acepto lo mejor ahora');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me abro a la belleza de la vida');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Presto atención a mi pensamiento y elijo conscientemente pensamientos saludables');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Acepto el desafío de mejorar como persona');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Confío en la vida y ella me responde de la misma manera');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me alimento de forma saludable, hago ejercicio con frecuencia y recibo suficiente descanso');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('La energía positiva fluye dentro de mi');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Decreto que algo maravilloso está a punto de sucederme');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Puedo alcanzar hasta mis sueños más locos');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('El éxito es inevitable en mi vida');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Le doy la bienvenida a nuevas ideas y puntos de vista');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Gracias porque cada día y en todos los sentidos estoy mejor, mejor y mejor');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('La vida y el universo están de mi parte, me apoyan totalmente y me proporcionan todo lo que necesito');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Estoy a cargo, ahora recupero mi propio poder');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Mis intuiciones son acertadas, estoy enfocado a las cosas que deseo y que son positivas para mi');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('He renunciado a toda la programación mental negativa que condicionaba mis decisiones');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Doy lo mejor de mi en cada situación');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Escucho mis sensaciones y soy amable conmigo mismo');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me divierto haciendo lo que hago en mi día a día');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Dejo ir todos mis miedos y dudas');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('La vida se vuelve sencilla y amorosa para mi');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Soy la energía que quiero atraer');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Soy belleza y nadie puede convencerme de lo contrario');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me amo y estoy orgullosa de lo que he logrado');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Tengo el poder de crear la vida que deseo');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me siento muy feliz y cómoda siendo yo misma');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Reconozco mis talentos, mis cualidades y mi belleza');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me estoy enamorando de mi');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me amo incondicionalmente y me acepto tal y como soy');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Elijo dejar de disculparme por ser yo misma');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Yo irradio confianza y armonía interior');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Soy la energía que quiero atraer');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Soy belleza y nadie puede convencerme de lo contrario');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me amo y estoy orgullosa de lo que he logrado');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Tengo el poder de crear la vida que deseo');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me siento muy feliz y cómoda siendo yo misma');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Reconozco mis talentos, mis cualidades y mi belleza');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me estoy enamorando de mi');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me amo incondicionalmente y me acepto tal y como soy');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Elijo dejar de disculparme por ser yo misma');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Yo irradio confianza y armonía interior');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Amo a mi cuerpo y todo lo que hace por mi');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Hoy elijo ver la perfección divina que reside en cada célula de mi cuerpo');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Soy talentosa y aprendo cada día nuevas formas de apreciarme');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Yo tengo confianza en mis capacidades y en mi criterio y se que puedo lograr cualquier cosa');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Soy merecedora del amor en todas sus formas y expresiones');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me doy permiso de enfocarme en lo que me gusta de mí misma');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Supero las creencias negativas que tengo sobre mí');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Me deshago de mis miedos y me permito confiar en mi cuerpo');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Mi belleza interior se refleja en cada parte de mi cuerpo y personalidad');
INSERT INTO "amorpropio" ("afirmaciones") VALUES ('Entre más me amo de manera incondicional, más amor llega a mi vida');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Vivo mi presente con entusiasmo.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Vivo aquí y ahora y lo disfruto plenamente.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Me permito disfrutar al máximo cada experiencia que vivo en el presente.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Mi mente está en paz.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Disfruto este momento único e irrepetible de mi vida..');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Vivo en el presente y tengo confianza en el futuro.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Me doy permiso de experimentar al máximo mi presente, mi ahora.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Todo está bien en mi mundo. Vivo feliz y en armonía.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Dejo ir el pasado y disfruto plenamente el presente.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Estoy emocionado de ver lo que depara el día de hoy.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Ahora me siento feliz.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Saboreo las experiencias que vivo en este momento.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Mi mente y mi corazón están conectados y alineados con el momento presente.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Mis días están llenos de bendiciones cada minuto.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Estoy dispuesta a disfrutar y saborear más el momento presente.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Me siento maravillosamente tranquilo y relajado.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Me siento feliz y me siento amada, aquí y ahora.');
INSERT INTO "atencion" ("afirmaciones") VALUES ('Estoy en conexión plena con este momento que vivo.');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Cada noche duermo tranquilamente');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Cada noche tengo buenos sueños');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Dejo ir el miedo, la preocupación, la ira y la culpa');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Me relajo y duermo en paz');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Cada noche duermo plácidamente y sin interrupciones');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Me doy permiso para cerrar los ojos esta noche y despertarme renovado mañana');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Dejo ir toda mi ansiedad y me relajo respirando suavemente');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Mi descanso es profundo y reparador');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Puedo acostarme y dormir temprano si lo deseo');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Mi dormitorio es un lugar de paz y relajación');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Abrazo mis sueños');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Soy y tengo suficiente, y ahora me permito descansar');
INSERT INTO "dormir" ("afirmaciones") VALUES ('En mi sueño tengo la libertad de volver a encontrar la alegría y la paz');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Duermo tranquilamente sabiendo que he hecho todo lo que podía hacer hoy');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Estoy agradecido por la luz del día y por la oscuridad de la noche, en la que dormiré tranquilamente');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Mientras yo duermo, el universo se sigue moviendo a mi favor');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Entrego todas mis preocupaciones a mi Ser interno, y sé que en la mañana se presentarán las mejores soluciones');
INSERT INTO "dormir" ("afirmaciones") VALUES ('El universo manifiesta su perfección en mi vida');
INSERT INTO "dormir" ("afirmaciones") VALUES ('No permito que nada perturbe mi descanso');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Me entrego a mi descanso en estado de paz');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Mi cuerpo, mente y alma son dignos de descanso');
INSERT INTO "dormir" ("afirmaciones") VALUES ('He hecho lo mejor que he podido por hoy');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Me relajo y me dejo fluir con la vida y el sueño reparador');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Cada día mi cuerpo y mi mente descansan mejor');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Mi cuerpo se cura mientras duermo');
INSERT INTO "dormir" ("afirmaciones") VALUES ('El sueño es un proceso natural');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Solo me aferro a los sentimientos positivos que he experimentado en el día de hoy');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Dejo que la excitación del día se desvanezca');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Estoy entrando en un sueño profundo');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Estoy en control de mis patrones de sueño');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Libero la ansiedad y el estrés');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Dormir es muy fácil para mí');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Cuando entro en esta habitación y me meto en la cama por la noche, los pensamientos de hoy comienzan a suavizarse naturalmente');
INSERT INTO "dormir" ("afirmaciones") VALUES ('A medida que la noche se oscurece, mis preocupaciones se desvanecen');
INSERT INTO "dormir" ("afirmaciones") VALUES ('Dejo ir los pensamientos negativos y me quedo con los felices');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('No es divertido ser una víctima. Rechazo volver a sentirme una persona indefensa.  Reclamo mi fuerza');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Consigo la ayuda que necesito, y ésta puede llegar de cualquier parte. Mi sistema de apoyo es sólido y afectuoso a la vez');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Cuando cometo una equivocación, me doy cuenta que no es más que una parte de mi proceso de aprendizaje');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Mi corazón es el centro de mi poder.  Sigo a mi corazón');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('La abundancia fluye libremente a través de mí');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Expreso gratitud por todo el bien de mi vida.  Cada día me aporta maravillosas sorpresas nuevas');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Avanzo en la vida, sé que estoy a salvo y que cuento con la protección y guía Divina');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('No importa lo que digan o hagan los demás.  Lo que importa es cómo elijo reaccionar y lo que elijo creer acerca de mí misma');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Elijo sentirme bien respecto a mí mismo. Me merezco mi amor');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('El mejor regalo que puedo hacerme es mi amor incondicional');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('No es divertido ser una víctima. Rechazo volver a sentirme una persona indefensa. Reclamo mi fuerza');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Consigo la ayuda que necesito, y ésta puede llegar de cualquier parte. Mi sistema de apoyo es sólido y afectuoso a la vez');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Cuando cometo una equivocación, me doy cuenta que no es más que una parte de mi proceso de aprendizaje');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Mi corazón es el centro de mi poder. Sigo a mi corazón');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('La abundancia fluye libremente a través de mí');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Expreso gratitud por todo el bien de mi vida. Cada día me aporta maravillosas sorpresas nuevas');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Avanzo en la vida, sé que estoy a salvo y que cuento con la protección y guía Divina');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('No importa lo que digan o hagan los demás. Lo que importa es cómo elijo reaccionar y lo que elijo creer acerca de mí misma');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('El mejor regalo que puedo hacerme es mi amor incondicional');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Cierro los ojos, tengo pensamientos positivos e inhalo y exhalo bondad');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('No importa mi edad, siempre puedo aprender y lo hago con decisión');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Dejo ir toda la negatividad que hay en mi cuerpo y mi mente');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Me deshago de mis temores de la infancia. Me siento segura, soy un ser humano con poder');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Soy una persona capaz y puedo hacer frente a cualquier cosa');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Abandono todo el miedo y la duda; la vida se vuelve sencilla y fácil para mí');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Perdono a todas las personas de mi pasado que me han infligido algún daño.  Las libero con amor');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Sé que no me puedo responsabilizar por otras personas. Todos estamos bajo la ley de nuestra propia conciencia');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Me perdono por no ser una persona perfecta. Vivo de la mejor manera que sé');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('La puerta de mi corazón se abre hacia dentro. Paso del rencor al Amor');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('El pasado ha terminado, ya no tiene poder en el presente');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('No hay problema, ni demasiado grande ni demasiado pequeño, que el amor no pueda resolver');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Paso del perdón a la comprensión y siento compasión por todos');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Soy capaz de perdonar; soy afable, afectuoso y amable, y sé que la vida me ama');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Me libero en este momento de todos los traumas de mi infancia y vivo en el amor');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Todas las personas tienen algo que enseñarme.  Hay un propósito para que estemos juntos');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Todos los cambios que tengo ante mí en la vida son positivos');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Cada día me ofrece una nueva oportunidad.  El ayer ya ha concluido. Hoy es el primer día de mi futuro');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('No puedo cambiar a otras personas. Dejo a los demás ser como son y simplemente me amo tal como soy');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Me siento seguro cuando expreso mis sentimientos. Puedo estar sereno en cualquier situación');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Estoy en el lugar correcto, en el momento adecuado, haciendo lo correcto');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Cada pensamiento que pensamos está creando nuestro futuro');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Recuerda, te has estado criticando durante años y no ha funcionado. Intenta aprobarte y ver qué pasa');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('El amor es la gran cura milagrosa. Amarnos a nosotros mismos hace milagros en nuestras vidas');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('No soluciono problemas. Arreglo mi pensamiento. Entonces los problemas se solucionan solos');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Me he dado cuenta de que el Universo ama la Gratitud. Cuanto más agradecido estés, más golosinas obtendrás');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Estoy dispuesto a liberar la necesidad de ser indigno. Soy digno de lo mejor en la vida, y ahora con amor me permito aceptarlo');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('No importa dónde vivamos en el planeta o lo difícil que parezca nuestra situación, tenemos la capacidad de superar y trascender nuestras circunstancias');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('En el centro de mi ser hay un pozo infinito de amor');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Todo está bien. Todo está funcionando para mi mayor bien. Fuera de esta situación solo vendrá la buena voluntad. Estoy a salvo');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Algunas personas prefieren dejar el planeta que cambiar');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Abandono todo el miedo y la duda; la vida se vuelve sencilla y fácil para mí');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('El humor y la alegría contribuyen a mi bienestar general');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Cuando me equivoco, me doy cuenta que no es más que una parte de mi proceso de aprendizaje');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Soy una persona capaz y puedo hacer frente a cualquier cosa');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('No hay problema, ni demasiado grande ni demasiado pequeño, que el amor no pueda resolver');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Recuerda, en la gran infinidad de la vida, todo es perfecto, entero y completo, y también lo eres tú');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Sé que los viejos patrones negativos ya no me limitan. Me despojo de ellos sin esfuerzo');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Aprende del pasado y déjalo ir. Vive en el presente');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Hoy escucho mis sentimientos y soy amable conmigo mismo. Sé que todos mis sentimientos son mis amigos');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Todos los cambios que tengo ante mí en la vida son positivos');
INSERT INTO "louisehay" ("afirmaciones") VALUES ('Cada día es una nueva oportunidad. Elijo hacer de este un gran día');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy abierto/a a toda la riqueza que la vida tiene para ofrecer');
INSERT INTO "manana" ("afirmaciones") VALUES ('Confío en el universo y en los demás');
INSERT INTO "manana" ("afirmaciones") VALUES ('Vivo aquí y ahora');
INSERT INTO "manana" ("afirmaciones") VALUES ('Me conozco lo suficiente como para tomar decisiones inteligentes para mí mismo/a');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy viviendo la vida que deseo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Merezco lo mejor y acepto cada regalo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Todo está bien, todo está conseguido');
INSERT INTO "manana" ("afirmaciones") VALUES ('Cuando soy feliz atraigo a la gente feliz');
INSERT INTO "manana" ("afirmaciones") VALUES ('Todo está cambiando y es maravilloso formar parte del cambio');
INSERT INTO "manana" ("afirmaciones") VALUES ('Gozo de salud y dinero en abundancia');
INSERT INTO "manana" ("afirmaciones") VALUES ('Mis pensamientos crean mi realidad');
INSERT INTO "manana" ("afirmaciones") VALUES ('Hoy elijo sonreír');
INSERT INTO "manana" ("afirmaciones") VALUES ('Aprendo de cada error para continuar mejorando a diario');
INSERT INTO "manana" ("afirmaciones") VALUES ('Grandes cosas llegan hoy a mi vida');
INSERT INTO "manana" ("afirmaciones") VALUES ('Tengo las habilidades necesarias para resolver los retos que vengan hoy');
INSERT INTO "manana" ("afirmaciones") VALUES ('Mi sabiduría interior me ayuda a tomar buenas decisiones');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy agradecido/a de poder disfrutar de otro día');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy sano/a y me siento fuerte para empezar el día');
INSERT INTO "manana" ("afirmaciones") VALUES ('Me alimento de forma saludable, hago ejercicio con frecuencia y recibo suficiente descanso');
INSERT INTO "manana" ("afirmaciones") VALUES ('Aprendo de cada error para continuar mejorando a diario');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy abierto/a a toda la riqueza que la vida tiene para ofrecer');
INSERT INTO "manana" ("afirmaciones") VALUES ('Confío en el universo y en los demás');
INSERT INTO "manana" ("afirmaciones") VALUES ('Vivo aquí y ahora');
INSERT INTO "manana" ("afirmaciones") VALUES ('Me conozco lo suficiente como para tomar decisiones inteligentes para mí mismo/a');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy viviendo la vida que deseo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Merezco lo mejor y acepto cada regalo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Todo está bien, todo está conseguido');
INSERT INTO "manana" ("afirmaciones") VALUES ('Cuando soy feliz atraigo a la gente feliz');
INSERT INTO "manana" ("afirmaciones") VALUES ('Todo está cambiando y es maravilloso formar parte del cambio');
INSERT INTO "manana" ("afirmaciones") VALUES ('Gozo de salud y dinero en abundancia');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy feliz');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy valiosa');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy amada');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy perseverante');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy disciplinada');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy positiva');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy alegre');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy compasiva');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy amorosa');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy sabiduría');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy fuerte');
INSERT INTO "manana" ("afirmaciones") VALUES ('Creo en mí');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy exitosa');
INSERT INTO "manana" ("afirmaciones") VALUES ('Amo mi trabajo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Amo mi cuerpo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Amo mi vida');
INSERT INTO "manana" ("afirmaciones") VALUES ('Puedo hacerlo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Voy a lograrlo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Creo en mí');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy orgullosa de cada paso que doy');
INSERT INTO "manana" ("afirmaciones") VALUES ('Hoy decido ser feliz');
INSERT INTO "manana" ("afirmaciones") VALUES ('Me acepto incondicionalmente');
INSERT INTO "manana" ("afirmaciones") VALUES ('Me amo tal y como soy');
INSERT INTO "manana" ("afirmaciones") VALUES ('El Universo conspira a mi favor');
INSERT INTO "manana" ("afirmaciones") VALUES ('Mi espíritu es libre y ligero');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy creando mi vida justo como la soñé');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy un imán para el amor');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy un imán para la fortuna');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy un imán para la prosperidad');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy un imán para las amistades sinceras');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy tomando mejores decisiones cada día');
INSERT INTO "manana" ("afirmaciones") VALUES ('Merezco respeto');
INSERT INTO "manana" ("afirmaciones") VALUES ('El éxito es inevitable en mi vida');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy dueña de mi vida');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy un imán de la abundancia');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy viviendo mi vida soñada');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy ganando 10,000 dólares al mes');
INSERT INTO "manana" ("afirmaciones") VALUES ('Aprendo de mis errores');
INSERT INTO "manana" ("afirmaciones") VALUES ('Mi confianza no tiene límites');
INSERT INTO "manana" ("afirmaciones") VALUES ('No le temo a los desafíos');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy merecedora de todas las bendiciones que llegan a mi vida');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy más fuerte cada día');
INSERT INTO "manana" ("afirmaciones") VALUES ('Tengo el poder de crear la historia de mi vida');
INSERT INTO "manana" ("afirmaciones") VALUES ('Tengo confianza en mis habilidades');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy capaz de hacer realidad mis sueños');
INSERT INTO "manana" ("afirmaciones") VALUES ('Recibo amor de todos a mi alrededor');
INSERT INTO "manana" ("afirmaciones") VALUES ('Amo y disfruto la vida');
INSERT INTO "manana" ("afirmaciones") VALUES ('Siento amor y compasión por la humanidad');
INSERT INTO "manana" ("afirmaciones") VALUES ('Mis fortalezas me hacen sobresalir');
INSERT INTO "manana" ("afirmaciones") VALUES ('Tengo una vida llena de bendiciones');
INSERT INTO "manana" ("afirmaciones") VALUES ('Vivo mi presente');
INSERT INTO "manana" ("afirmaciones") VALUES ('Atraigo todo lo que deseo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Tomo decisiones inteligentes');
INSERT INTO "manana" ("afirmaciones") VALUES ('Tengo el poder de crear la vida que deseo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Puedo lograr lo que me propongo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Puedo ser quien quiera llegar a ser');
INSERT INTO "manana" ("afirmaciones") VALUES ('Puedo conseguir todo lo que deseo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Encuentro la felicidad en mi propia compañía');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy agradecida por todo lo que tengo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy en el camino correcto para cumplir todas mis metas');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy capaz de ajustarme a cualquier cambio');
INSERT INTO "manana" ("afirmaciones") VALUES ('El éxito está en mi futuro');
INSERT INTO "manana" ("afirmaciones") VALUES ('No aceptaré aquello que no me hace feliz');
INSERT INTO "manana" ("afirmaciones") VALUES ('Puedo alcanzar hasta mis sueños más locos');
INSERT INTO "manana" ("afirmaciones") VALUES ('Las críticas no me afectarán');
INSERT INTO "manana" ("afirmaciones") VALUES ('No me dejaré para después');
INSERT INTO "manana" ("afirmaciones") VALUES ('Mi situación actual no determinará mi destino final');
INSERT INTO "manana" ("afirmaciones") VALUES ('No gastaré mi energía en cosas que no aporten a mi vida');
INSERT INTO "manana" ("afirmaciones") VALUES ('No me pasaré la vida esperando');
INSERT INTO "manana" ("afirmaciones") VALUES ('No tengo que probarle nada a nadie');
INSERT INTO "manana" ("afirmaciones") VALUES ('No me quedaré con las ganas');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy capaz de reemplazar cualquier pensamiento negativo con energía positiva');
INSERT INTO "manana" ("afirmaciones") VALUES ('Decreto que algo maravilloso está a punto de sucederme');
INSERT INTO "manana" ("afirmaciones") VALUES ('Decreto que todos mis sueños pronto se harán realidad');
INSERT INTO "manana" ("afirmaciones") VALUES ('Decreto que encontraré el amor en cada aspecto de mi vida');
INSERT INTO "manana" ("afirmaciones") VALUES ('Decreto que tendré un día maravilloso');
INSERT INTO "manana" ("afirmaciones") VALUES ('Decreto que la vida me sonríe');
INSERT INTO "manana" ("afirmaciones") VALUES ('Soy más fuerte de lo que imaginaba');
INSERT INTO "manana" ("afirmaciones") VALUES ('Decreto que forjaré mi propio destino');
INSERT INTO "manana" ("afirmaciones") VALUES ('Decreto vivir con más esencia y hacerle menos caso a las apariencias');
INSERT INTO "manana" ("afirmaciones") VALUES ('Lo sueño, lo busco y lo consigo');
INSERT INTO "manana" ("afirmaciones") VALUES ('Mi relación con mi pareja es todo lo que siempre soñé');
INSERT INTO "manana" ("afirmaciones") VALUES ('Estoy rodeada de amor');
INSERT INTO "manana" ("afirmaciones") VALUES ('Atraigo a mi vida a las personas correctas');
INSERT INTO "manana" ("afirmaciones") VALUES ('Veo a mi prójimo con amor');
INSERT INTO "manana" ("afirmaciones") VALUES ('Mis acciones positivas se multiplican a mi favor');
INSERT INTO "manana" ("afirmaciones") VALUES ('Tengo la vida que siempre soñé');
INSERT INTO "mente" ("afirmaciones") VALUES ('Alcanzo las metas que me propongo.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Todos los días en todo lo que hago estoy mejor, mejor y mejor.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Tengo suficientes recursos personales para lograr éxito en mi vida.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Estoy en paz con el que mundo que me rodea y el mundo está en paz conmigo.');
INSERT INTO "mente" ("afirmaciones") VALUES ('En mi vida siempre hay abundancia de recursos.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Encuentro felicidad y placer en las cosas más simples de la vida.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Mi mente está preparada para aprender cosas nuevas.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Puedo alcanzar la grandeza mientras desarrollo mi potencial.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Mi potencial para tener éxito es infinito.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Elijo saborear cada segundo de mi vida.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Hoy todas las puertas se abren para mí.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Soy creativo y lleno de ideas brillantes.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Tengo la capacidad de crear y lograr lo que deseo.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Soy el creador de mi realidad.');
INSERT INTO "mente" ("afirmaciones") VALUES ('La vida es fácil y divertida.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Todo funciona para mi mayor bien.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Soy un ser espiritual que tiene una experiencia física.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Merezco una vida abundante, llena de amor y felicidad.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Todo llega a mi vida con facilidad, gozo y gloria.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Estoy abierta a cambiar de actitud y vivir feliz.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Maravillosas sorpresas llegan todos los días a mí.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Merezco que sucedan cosas maravillosas en mi vida.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Recibo con amor y alegría los momentos maravillosos que fluyen a mí constantemente.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Siempre tengo todo lo que necesito.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Tengo la capacidad de crear y lograr lo que deseo.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Soy amado y apoyado por el universo.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Estoy dispuesta a desaprender antiguos patrones.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Confío en que soy guiada para dar resultados maravillosos y sorprendentes.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Recibo y doy amor ilimitado.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Disfruto de mi energía y mi buena actitud.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Elijo vivir con paz en mi interior.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Hoy es un día lleno de oportunidades y abro mi corazón para recibirlas.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Doy las gracias por el flujo ilimitado de cosas buenas en mi vida.');
INSERT INTO "mente" ("afirmaciones") VALUES ('Estoy eternamente agradecido por el amor que soy capaz de dar y por el amor que aún tengo que recibir');
INSERT INTO "mente" ("afirmaciones") VALUES ('Hoy me espera un excelente día y lo voy a disfrutar al máximo');
INSERT INTO "mente" ("afirmaciones") VALUES ('Pase lo que pase, estoy seguro de que puedo volver a estar agradecido');
INSERT INTO "mente" ("afirmaciones") VALUES ('Gracias por que tengo a mi familia, a mis seres queridos y a mis amigos');
INSERT INTO "mente" ("afirmaciones") VALUES ('Estoy agradecido ahora, y eso es mantener la puerta abierta para recibir más bendiciones');
INSERT INTO "mente" ("afirmaciones") VALUES ('Doy la bienvenida a todas las formas en que el universo quiere bendecirme');
INSERT INTO "mente" ("afirmaciones") VALUES ('Gracias porque todo mi cuerpo está sano, fuerte y con energía suficiente');
INSERT INTO "mente" ("afirmaciones") VALUES ('Confío en que el universo está apoyando mi mayor bien');
INSERT INTO "mente" ("afirmaciones") VALUES ('Gracias porque estoy en el lugar perfecto y en el momento oportuno, haciendo lo adecuado');
INSERT INTO "mente" ("afirmaciones") VALUES ('El sentimiento de agradecimiento amplía mi perspectiva y me abre a nuevas formas de vivir feliz en este mundo; es como si todo el universo estuviera en mi corazón');
INSERT INTO "mente" ("afirmaciones") VALUES ('Estoy eternamente agradecido por el amor que soy capaz de dar y por el amor que aún tengo que recibir');
INSERT INTO "mente" ("afirmaciones") VALUES ('Hoy me espera un excelente día y lo voy a disfrutar al máximo');
INSERT INTO "mente" ("afirmaciones") VALUES ('Pase lo que pase, estoy seguro de que puedo volver a estar agradecido');
INSERT INTO "mente" ("afirmaciones") VALUES ('Gracias por que tengo a mi familia, a mis seres queridos y a mis amigos');
INSERT INTO "mente" ("afirmaciones") VALUES ('Estoy agradecido ahora, y eso es mantener la puerta abierta para recibir más bendiciones');
INSERT INTO "mente" ("afirmaciones") VALUES ('Doy la bienvenida a todas las formas en que el universo quiere bendecirme');
INSERT INTO "mente" ("afirmaciones") VALUES ('Gracias porque todo mi cuerpo está sano, fuerte y con energía suficiente');
INSERT INTO "mente" ("afirmaciones") VALUES ('Confío en que el universo está apoyando mi mayor bien');
INSERT INTO "mente" ("afirmaciones") VALUES ('Gracias porque estoy en el lugar perfecto y en el momento oportuno, haciendo lo adecuado');
INSERT INTO "mente" ("afirmaciones") VALUES ('El sentimiento de agradecimiento amplía mi perspectiva y me abre a nuevas formas de vivir feliz en este mundo; es como si todo el universo estuviera en mi corazón');
INSERT INTO "mente" ("afirmaciones") VALUES ('Mi acción de gracias se extiende mucho más allá de mis pensamientos; aporto un espíritu agradecido a cada paso y acción que doy');
INSERT INTO "mente" ("afirmaciones") VALUES ('Gracias porque todas mis relaciones son armoniosas');
INSERT INTO "mente" ("afirmaciones") VALUES ('Hago brillar la luz del aprecio sobre una situación que de otro modo sería oscura; no hay oscuridad que pueda escapar de esa luz por mucho tiempo');
INSERT INTO "mente" ("afirmaciones") VALUES ('Gracias porque me siento bien con todas las personas');
INSERT INTO "mente" ("afirmaciones") VALUES ('Hoy me asocio con la paz y lo hago a través del poder de mantener un corazón agradecido');
INSERT INTO "mente" ("afirmaciones") VALUES ('Gracias por toda la abundancia y prosperidad que hay en mi vida');
INSERT INTO "mente" ("afirmaciones") VALUES ('Gracias por todo lo que soy y todo lo que tengo');
INSERT INTO "mente" ("afirmaciones") VALUES ('En cambio, elijo ver la paz');
INSERT INTO "mente" ("afirmaciones") VALUES ('Vivo todos los momentos de mi vida con amplia gratitud');
INSERT INTO "mente" ("afirmaciones") VALUES ('La gratitud es un hábito que cultivo diariamente');
INSERT INTO "mente" ("afirmaciones") VALUES ('Acepto agradecidamente los regalos que me da la vida');
INSERT INTO "mente" ("afirmaciones") VALUES ('Estoy agradecida porque tengo un techo donde refugiarme');
INSERT INTO "mente" ("afirmaciones") VALUES ('Hoy agradezco las lecciones y el aprendizaje que la vida me da');
INSERT INTO "mente" ("afirmaciones") VALUES ('Doy gracias por mi vida y salud diariamente');
INSERT INTO "mente" ("afirmaciones") VALUES ('Gracias por otra oportunidad de ser mejor que ayer');
INSERT INTO "mente" ("afirmaciones") VALUES ('Doy gracias por este bello día');
INSERT INTO "mente" ("afirmaciones") VALUES ('Vivo en un universo lleno de abundancia, y agradezco por ello');
INSERT INTO "mente" ("afirmaciones") VALUES ('Hoy agradezco los bienes que poseo y las bendiciones que recibo cada día');
INSERT INTO "mente" ("afirmaciones") VALUES ('Agradezco profundamente a mi cuerpo y a mi mente por todo el trabajo que han hecho hoy');
INSERT INTO "mente" ("afirmaciones") VALUES ('Siento gratitud por toda mi existencia');
INSERT INTO "mente" ("afirmaciones") VALUES ('Elijo ver esta temporada de mi vida, entonces, a través de los ojos del aprecio, lo mejor que pueda');
INSERT INTO "mente" ("afirmaciones") VALUES ('Estoy dispuesto a confiar en que mi vida es exactamente como debe ser');
INSERT INTO "mente" ("afirmaciones") VALUES ('Puedo relajarme un poco y estar agradecido por lo que tengo ahora');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Genero riqueza económica con todo lo que hago.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Estoy en el proceso de construir un negocio exitoso.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Mi ambiente de trabajo es tranquilo y relajado.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Vender es algo natural en mí.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Mi negocio es un lugar tranquilo, amoroso y lleno de gente maravillosa y talentosa.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('A través de mi negocio hago una gran diferencia en este mundo.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Me siento feliz en mi negocio y mi trabajo.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Cada día nuevos clientes solicitan mis productos o servicios.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Estoy feliz y agradecida porque mi negocio se fortalece y crece todos los días.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Mi trabajo me permite expresar mis talentos y habilidades.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Agradezco los cambios como oportunidades para avanzar y progresar.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Cada desafío, dificultad o fracaso me han convertido en un mejor hombre(o mujer) de negocios.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Vivo un excelente año y atraigo las mejores opciones para mí.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Cada día nuevas y mejores oportunidades se presentan a mi puerta.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Doy lo mejor de mi en mi negocio.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Elijo los caminos más convenientes y prósperos para mi empresa.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Mis ingresos se multiplican exponencialmente cada día.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Estoy abierta a ser una profesional reconocida, famosa y muy solicitada.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Mi emprendimiento se expande y crece más cada día.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Soy creativa, ingeniosa y persuasiva y vendo con entusiasmo mis ideas y proyectos.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Soy excelente en todo lo que hago y genero abundantes ganancias con mis proyectos.');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Tengo las habilidades y el conocimiento para tomar las mejores decisiones para mi carrera');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Estoy enfocado y apasionado por mis objetivos y mi carrera');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Tengo el impulso y la ambición para lograr mis objetivos');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Me permito crecer y aprender');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Confío en mis habilidades para alcanzar la cima de mi profesión');
INSERT INTO "negocio" ("afirmaciones") VALUES ('No importa dónde esté, solo hay un bien infinito, una sabiduría infinita, una armonía y un amor infinitos');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Mi alegría me permite expresar mis talentos y habilidades, y estoy agradecida por este empleo');
INSERT INTO "negocio" ("afirmaciones") VALUES ('En mi trabajo, mis compañeros de trabajo y yo fomentamos el crecimiento y el éxito de los demás');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Cuando me despierto por la mañana, planeo un buen día');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Realmente creo que nosotros estamos aquí para bendecirnos el uno al otro');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Tengo facilidad para hablar frente a otros');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Cuando me encuentro con problemas en el trabajo, estoy dispuesta a solicitar ayuda');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Creo un buen sentimiento en el trabajo');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Sé que cuando hago lo mejor en mi trabajo, me recompensan de todas las formas');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Avanzo fácil y rápidamente en la realización de mis trabajos');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Soy una persona muy eficiente en todo lo que hago');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Trabajo en un lugar armonioso, con buen horario y bien pagado');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Aprendo a diario mejores estrategias');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Me siento orgulloso del éxito en mi trabajo');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Agradezco verme como una persona exitosa y satisfecha');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Agradezco la vida maravillosa y los gustos que me puedo dar a mí y a mis seres queridos gracias a la excelente remuneración que recibo por mi trabajo');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Agradezco por tener las mejores capacidades para desempeñar el empleo que tanto me gusta');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Tengo todas las habilidades y conocimientos para cumplir con el trabajo de mis sueños');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Soy el candidato perfecto para este puesto');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Decreto que soy feliz y que el empleo que tengo es perfecto para mí, porque ahora el dinero me pertenece y me llega en abundancia');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Tengo la seguridad de que voy a conseguir un mejor empleo con éxito y felicidad');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Agradezco el ambiente laboral en el que me muevo');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Tengo confianza en mí mismo');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Abro mi corazón para recibir esta energía maravillosa de abundancia y seguridad que atrae el trabajo de mis sueños ahora');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Atraigo todo lo necesario para lograr mis metas laborales');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Tengo las habilidades y el conocimiento para tomar las mejores decisiones para mi carrera');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Estoy enfocado y apasionado por mis objetivos y mi carrera');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Tengo el impulso y la ambición para lograr mis objetivos');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Me permito crecer y aprender');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Confío en mis habilidades para alcanzar la cima de mi profesión');
INSERT INTO "negocio" ("afirmaciones") VALUES ('No importa dónde esté, solo hay un bien infinito, una sabiduría infinita, una armonía y un amor infinitos');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Mi alegría me permite expresar mis talentos y habilidades, y estoy agradecida por este empleo');
INSERT INTO "negocio" ("afirmaciones") VALUES ('En mi trabajo, mis compañeros de trabajo y yo fomentamos el crecimiento y el éxito de los demás');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Cuando me despierto por la mañana, planeo un buen día');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Realmente creo que nosotros estamos aquí para bendecirnos el uno al otro');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Mi anticipación atrae experiencias positivas');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Reflejo esta creencia en mis interacciones diarias');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Tengo confianza en mí mismo');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Me doy cuenta de que hay leyes que gobiernan el universo y yo trabajo con estas leyes en todos los ámbitos de mi vida');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Me siento cómodo hablando en presencia de compañeros de trabajo');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Mi anticipación atrae experiencias positivas');
INSERT INTO "negocio" ("afirmaciones") VALUES ('Reflejo esta creencia en mis interacciones diarias');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Estoy rodeada de abundancia.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Atraigo dinero fácil y sin esfuerzo.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Estoy abierto a toda la riqueza que la vida tiene para ofrecer.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Amo al dinero y el dinero me ama.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Veo abundancia en todas partes.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Soy financieramente libre y abundante.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Gran prosperidad está fluyendo hacia mí ahora.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Atraigo prosperidad donde quiera que vaya.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('La abundancia es mi estado natural y yo lo acepto.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Permito que la prosperidad y la abundancia de amor entren en mi vida y lo disfruto.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Siempre se me ocurren ideas que atraen más riqueza.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Hoy está lleno de oportunidades que aprovecho.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('El universo me proporciona la prosperidad que merezco,');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Veo abundancia en mi vida.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('El dinero que gano me permite contribuir y retribuir al mundo.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Estoy dispuesta a llevar una vida próspera y feliz.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Tengo múltiples fuentes de ingreso que crecen cada día.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Mi vida está llena de prosperidad.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Mis ingresos se multiplican de formas inesperadas.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Estoy agradecida con el universo que me proporciona gran prosperidad y riqueza.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Soy próspera, el dinero fluye hacia mí de muchas fuentes.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Gracias universo por mi gran prosperidad.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Cada día soy más y más próspero.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Suelto toda resistencia a la prosperidad y me llega de forma natural.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('El dinero fluye hacia mí de fuentes esperadas e inesperadas.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Poseo una mentalidad millonaria.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('La prosperidad apoya mi felicidad.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('El dinero amplifica las oportunidades y experiencias en mi vida.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('El dinero y la prosperidad fluyen libremente en mi vida.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('La prosperidad perfecta es mi realidad elegida.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Vivo en un universo abundante libre de toda carencia.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Estoy destinada a encontrar la prosperidad en todo lo que hago.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Mi energía está alineada con la energía y la vibración de la prosperidad.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Todo lo que hago me permite ganar más dinero.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Estoy abierta a la posibilidad de que mis recursos son inagotables e inmediatos.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Todo lo que hay en el universo, visible o invisible, trabaja para mi prosperidad.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Mis ingresos financieros son ilimitados.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Mi cuenta bancaria aumenta cada día.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('El dinero trae alegría y bienestar a mi vida.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Produzco riqueza económica trabajando en mis pasiones.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Tengo un suministro infinito de riqueza.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Me permito tener más de lo que jamás imaginé.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Cada día en todos los sentidos mi prosperidad va en aumento');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Aprecio y agradezco toda la prosperidad en mi vida.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Elijo vivir en abundancia y prosperidad.');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Amo al dinero. El dinero me ama');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Siempre tengo ideas para generar dinero');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Estoy recibiendo dinero ahora mismo');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Siento abundancia en todos los aspectos de mi vida');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Tengo más que suficiente dinero');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('La riqueza fluye hacia mí en todas las áreas de mi vida. Doy gracias por la capacidad que tengo para atraer riqueza y abundancia');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Mis ingresos son cada vez más y más');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('El dinero fluye libremente y en abundancia en mi vida');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Estoy cada vez más magnético al dinero, la prosperidad y la abundancia');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('El dinero es una parte integral de mi vida y nunca se encuentra lejos de mí');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Puedo crear dinero y abundancia a través de la alegría, la vitalidad y el amor propio');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Permito que mis ingresos se expandan constantemente y siempre vivo en comunidad y felicidad');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Soy próspero, en mi fluye una corriente inagotable de riqueza');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('El éxito financiero es mío y lo acepto ahora mismo');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Hablo de éxito y prosperidad. Mis palabras elevan e inspiran a otros');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Entre más contribuyo hacia los demás, más dinero soy capaz de generar');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Yo vivo una vida abundante, la riqueza vino para quedarse en mi vida');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Estoy atrayendo toda la abundancia que deseo a mi vida fácilmente');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Como puedo hacer lo que me gusta, el dinero y el flujo de la abundancia vienen libremente a mí');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Estoy atrayendo toda la prosperidad financiera');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Me despierto cada mañana emocionada por trabajar en mi pasión y generar riqueza de ella');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Cada día, mi vida está llena de las maravillas y la magia de la abundancia');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Yo fluyo armónicamente con la energía del dinero');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Dejo ir toda resistencia a la prosperidad y viene a mí fácilmente');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Ser rica me da alegría, felicidad y tranquilidad');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Soy abundante y siempre tengo lo suficiente para mí y mi familia');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('La riqueza es mi derecho divino, es mi estado natural de ser');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Yo siempre tengo todo lo que necesito');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Me visualizo fácilmente teniendo una abundancia ilimitada');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Declaro abundancia dentro de mí y a mi alrededor');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Soy naturalmente abundante y próspero');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Paso del pensamiento de la pobreza al pensamiento de la prosperidad');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Atraigo sin esfuerzo toda la prosperidad que necesito y deseo');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Libero mi mente de los pensamientos de escases');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Libero toda oposición a la riqueza');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Yo soy ilimitado cuando se trata de dinero, riqueza y prosperidad');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('El dinero me encuentra');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Siempre tengo el dinero suficiente para cumplir mis sueños');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Todo dinero que gasto vuelve a mí multiplicado');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Veo venir grandes cantidades de dinero hacia mí');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Nuevas fuentes de ingresos se presentan ante mí');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Dejo ir, en este momento, cualquier creencia negativa acerca del dinero');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Me siento sumamente agradecida por todo lo que tengo');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Merezco ser una persona rica y abundante');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Quiero, puedo, y me lo merezco');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Soy una persona alineada con la energía de la riqueza');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Merezco seguridad financiera y todo lo que trae hacia mí');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Agradezco todo el dinero que está presente en mi vida');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Invierto mi dinero conscientemente');
INSERT INTO "riqueza" ("afirmaciones") VALUES ('Soy capaz de crear la vida que deseo');
INSERT INTO "salud" ("afirmaciones") VALUES ('Cada célula de mi cuerpo vibra con energía saludable.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Disfruto de plena salud y altas dosis de energía.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi cuerpo tiene el poder de sanarse solo.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Practico hábitos maravillosos y útiles para mi salud.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Confío en que la vida siempre me apoya.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Elijo disfrutar y saborear cada minuto de mi día.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Cada célula de mi cuerpo está sana y llena de amor.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Disfruto de excelente salud y vivo lleno de energía.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Todos los días me pongo y me siento más saludable.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Me libero del pasado y vivo en el presente.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi cuerpo se comunica conmigo y yo lo escucho.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi sistema inmunológico se fortalece cada día.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Estoy alineada con el universo.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Gozo de una salud perfecta.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Atraigo a mi vida todo lo que requiero para mantenerme sana.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Agradezco el privilegio de vivir en mi cuerpo.');
INSERT INTO "salud" ("afirmaciones") VALUES ('El amor me rodea y protege mi cuerpo.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Libero y dejo ir a todos los modelos mentales que me generan malestar.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Realizo ejercicios físicos con entusiasmo.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Acepto la perfecta salud como el estado natural de mi ser.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Cada célula de mi cuerpo funciona perfectamente.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi mente, cuerpo, emociones y espíritu están en equilibrio.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Soy un ser espiritual que está divinamente guiado.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Estimulo mi sistema inmunológico con una dieta balanceada.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Me enfoco en pensamientos que me nutren y mantienen alta mi vibración.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Afecto la perfecta salud como el estado natural de mi ser.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Tengo una salud integral maravillosa, me siento fuerte y llena de vida.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Estoy dispuesta a dormir lo suficiente para amanecer llena de energía.');
INSERT INTO "salud" ("afirmaciones") VALUES ('La gracia y el amor de Dios trabajan a través de mí.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi cuerpo funciona de la mejor manera todo el tiempo.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Me siento fuerte y con gran energía.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi salud es uno de los grandes tesoros de mi vida.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi cuerpo es saludable, fuerte y flexible.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Presto atención a mi cuerpo todos los días.');
INSERT INTO "salud" ("afirmaciones") VALUES ('Tengo un cuerpo rebosante de salud y vida.');
INSERT INTO "salud" ("afirmaciones") VALUES ('La luz de Cristo penetra ahora en cada célula de mi cuerpo, doy las gracias por mi salud radiante');
INSERT INTO "salud" ("afirmaciones") VALUES ('Soy una persona saludable');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi cuerpo está trabajando para mantenerme saludable y fuerte');
INSERT INTO "salud" ("afirmaciones") VALUES ('Me encanta cuidar de mi cuerpo y de mi salud');
INSERT INTO "salud" ("afirmaciones") VALUES ('Me demuestro amor propio a través de los alimentos que consumo y las cosas que pienso');
INSERT INTO "salud" ("afirmaciones") VALUES ('Cada uno de mis órganos es un motor lleno de vitalidad');
INSERT INTO "salud" ("afirmaciones") VALUES ('Estoy llena/o de energía y de vitalidad');
INSERT INTO "salud" ("afirmaciones") VALUES ('Hago ejercicios porque amo mi cuerpo y porque celebro todas las cosas que mi cuerpo hace por mí');
INSERT INTO "salud" ("afirmaciones") VALUES ('Sé que cualquier molestia física es pasajera, todo está volviendo a la normalidad en este instante');
INSERT INTO "salud" ("afirmaciones") VALUES ('Escucho atentamente a mi cuerpo, escucho sus necesidades y las cosas que quiere');
INSERT INTO "salud" ("afirmaciones") VALUES ('Me preocupo cada día por aprender hábitos saludables');
INSERT INTO "salud" ("afirmaciones") VALUES ('Paso tiempo con gente positiva y saludable');
INSERT INTO "salud" ("afirmaciones") VALUES ('Tengo la fortaleza para enfrentar cualquier situación difícil y cambiar su rumbo');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi salud es extraordinaria, perfecta, no tengo nada por lo cual quejarme');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi cuerpo es mi templo, por lo que siempre lo cuido y lo mantengo en forma');
INSERT INTO "salud" ("afirmaciones") VALUES ('Cada inhalación me llena de luz y energía');
INSERT INTO "salud" ("afirmaciones") VALUES ('Yo soy vida');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi alma se encuentra alojada en un cuerpo perfecto');
INSERT INTO "salud" ("afirmaciones") VALUES ('El amor que está en mi corazón fluye por todo mi cuerpo y me hace cada vez más sano');
INSERT INTO "salud" ("afirmaciones") VALUES ('La perfecta relación cuerpo-mente-alma sana todo mi ser');
INSERT INTO "salud" ("afirmaciones") VALUES ('Me rodeo de la gente que me hace sentir bien');
INSERT INTO "salud" ("afirmaciones") VALUES ('Tengo una salud envidiable, en mi mente predominan pensamientos de amor, amor hacia mi cuerpo');
INSERT INTO "salud" ("afirmaciones") VALUES ('A partir de este momento quedo libre de todo mal ocasionado por la enfermedad y recupero la fortaleza que hay en mi interior, por que estoy seguro de que este es el anhelo del Universo');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi cuerpo es saludable');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mis células, órganos y sistemas funcionan correctamente, permitiéndome tener un cuerpo sano y lleno de energía');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi prioridad en la vida es mantenerme sana');
INSERT INTO "salud" ("afirmaciones") VALUES ('Amo cada una de las partículas que conforman mi organismo');
INSERT INTO "salud" ("afirmaciones") VALUES ('A diario, agradezco por la excelente salud que tengo y por el maravilloso funcionamiento de mi cuerpo');
INSERT INTO "salud" ("afirmaciones") VALUES ('Estoy libre de las tensiones, me permito ser paciente y me tomo tiempo suficiente para descansar, ya que comprendo que ésta es la forma para liberar al cuerpo de la tensión');
INSERT INTO "salud" ("afirmaciones") VALUES ('La actividad física me permite despejar mi mente y expulsar por mis poros todas aquellas toxinas que se encuentran en mi cuerpo');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi cuerpo está sanando y me siento mejor cada día');
INSERT INTO "salud" ("afirmaciones") VALUES ('Soy una persona saludable');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi cuerpo está trabajando para mantenerme saludable y fuerte');
INSERT INTO "salud" ("afirmaciones") VALUES ('Me encanta cuidar de mi cuerpo y de mi salud');
INSERT INTO "salud" ("afirmaciones") VALUES ('Me demuestro amor propio a través de los alimentos que consumo y las cosas que pienso');
INSERT INTO "salud" ("afirmaciones") VALUES ('Cada uno de mis órganos es un motor lleno de vitalidad');
INSERT INTO "salud" ("afirmaciones") VALUES ('Estoy llena/o de energía y de vitalidad');
INSERT INTO "salud" ("afirmaciones") VALUES ('Hago ejercicios porque amo mi cuerpo y porque celebro todas las cosas que mi cuerpo hace por mí');
INSERT INTO "salud" ("afirmaciones") VALUES ('Sé que cualquier molestia física es pasajera, todo está volviendo a la normalidad en este instante');
INSERT INTO "salud" ("afirmaciones") VALUES ('Escucho atentamente a mi cuerpo, escucho sus necesidades y las cosas que quiere');
INSERT INTO "salud" ("afirmaciones") VALUES ('Me preocupo cada día por aprender hábitos saludables');
INSERT INTO "salud" ("afirmaciones") VALUES ('Mi alma está tranquila');
COMMIT;
