BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "dormir" (
	"id"	INTEGER NOT NULL UNIQUE,
	"afirmaciones"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "manana" (
	"id"	INTEGER NOT NULL UNIQUE,
	"afirmaciones"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "riqueza" (
	"id"	INTEGER NOT NULL UNIQUE,
	"afirmaciones"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "louisehay" (
	"id"	INTEGER NOT NULL UNIQUE,
	"afirmaciones"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "amorpropio" (
	"id"	INTEGER NOT NULL UNIQUE,
	"afirmaciones"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "amor" (
	"id"	INTEGER NOT NULL UNIQUE,
	"afirmaciones"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "atencion" (
	"id"	INTEGER NOT NULL UNIQUE,
	"afirmaciones"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "mente" (
	"id"	INTEGER NOT NULL UNIQUE,
	"afirmaciones"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "negocio" (
	"id"	INTEGER NOT NULL UNIQUE,
	"afirmaciones"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "salud" (
	"id"	INTEGER NOT NULL UNIQUE,
	"afirmaciones"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "dormir" VALUES (1,'Cada noche duermo tranquilamente');
INSERT INTO "dormir" VALUES (2,'Cada noche tengo buenos sueños');
INSERT INTO "dormir" VALUES (3,'Dejo ir el miedo, la preocupación, la ira y la culpa');
INSERT INTO "dormir" VALUES (4,'Me relajo y duermo en paz');
INSERT INTO "dormir" VALUES (5,'Cada noche duermo plácidamente y sin interrupciones');
INSERT INTO "dormir" VALUES (6,'Me doy permiso para cerrar los ojos esta noche y despertarme renovado mañana');
INSERT INTO "dormir" VALUES (7,'Dejo ir toda mi ansiedad y me relajo respirando suavemente');
INSERT INTO "dormir" VALUES (8,'Mi descanso es profundo y reparador');
INSERT INTO "dormir" VALUES (9,'Puedo acostarme y dormir temprano si lo deseo');
INSERT INTO "dormir" VALUES (10,'Mi dormitorio es un lugar de paz y relajación');
INSERT INTO "dormir" VALUES (11,'Abrazo mis sueños');
INSERT INTO "dormir" VALUES (12,'Soy y tengo suficiente, y ahora me permito descansar');
INSERT INTO "dormir" VALUES (13,'En mi sueño tengo la libertad de volver a encontrar la alegría y la paz');
INSERT INTO "dormir" VALUES (14,'Duermo tranquilamente sabiendo que he hecho todo lo que podía hacer hoy');
INSERT INTO "dormir" VALUES (15,'Estoy agradecido por la luz del día y por la oscuridad de la noche, en la que dormiré tranquilamente');
INSERT INTO "dormir" VALUES (16,'Mientras yo duermo, el universo se sigue moviendo a mi favor');
INSERT INTO "dormir" VALUES (17,'Entrego todas mis preocupaciones a mi Ser interno, y sé que en la mañana se presentarán las mejores soluciones');
INSERT INTO "dormir" VALUES (18,'El universo manifiesta su perfección en mi vida');
INSERT INTO "dormir" VALUES (19,'No permito que nada perturbe mi descanso');
INSERT INTO "dormir" VALUES (20,'Me entrego a mi descanso en estado de paz');
INSERT INTO "dormir" VALUES (21,'Mi cuerpo, mente y alma son dignos de descanso');
INSERT INTO "dormir" VALUES (22,'He hecho lo mejor que he podido por hoy');
INSERT INTO "dormir" VALUES (23,'Me relajo y me dejo fluir con la vida y el sueño reparador');
INSERT INTO "dormir" VALUES (24,'Cada día mi cuerpo y mi mente descansan mejor');
INSERT INTO "dormir" VALUES (25,'Mi cuerpo se cura mientras duermo');
INSERT INTO "dormir" VALUES (26,'El sueño es un proceso natural');
INSERT INTO "dormir" VALUES (27,'Solo me aferro a los sentimientos positivos que he experimentado en el día de hoy');
INSERT INTO "dormir" VALUES (28,'Dejo que la excitación del día se desvanezca');
INSERT INTO "dormir" VALUES (29,'Estoy entrando en un sueño profundo');
INSERT INTO "dormir" VALUES (30,'Estoy en control de mis patrones de sueño');
INSERT INTO "dormir" VALUES (31,'Libero la ansiedad y el estrés');
INSERT INTO "dormir" VALUES (32,'Dormir es muy fácil para mí');
INSERT INTO "dormir" VALUES (33,'Cuando entro en esta habitación y me meto en la cama por la noche, los pensamientos de hoy comienzan a suavizarse naturalmente');
INSERT INTO "dormir" VALUES (34,'A medida que la noche se oscurece, mis preocupaciones se desvanecen');
INSERT INTO "dormir" VALUES (35,'Dejo ir los pensamientos negativos y me quedo con los felices');
INSERT INTO "manana" VALUES (1,'Estoy abierto/a a toda la riqueza que la vida tiene para ofrecer');
INSERT INTO "manana" VALUES (2,'Confío en el universo y en los demás');
INSERT INTO "manana" VALUES (3,'Vivo aquí y ahora');
INSERT INTO "manana" VALUES (4,'Me conozco lo suficiente como para tomar decisiones inteligentes para mí mismo/a');
INSERT INTO "manana" VALUES (5,'Estoy viviendo la vida que deseo');
INSERT INTO "manana" VALUES (6,'Merezco lo mejor y acepto cada regalo');
INSERT INTO "manana" VALUES (7,'Todo está bien, todo está conseguido');
INSERT INTO "manana" VALUES (8,'Cuando soy feliz atraigo a la gente feliz');
INSERT INTO "manana" VALUES (9,'Todo está cambiando y es maravilloso formar parte del cambio');
INSERT INTO "manana" VALUES (10,'Gozo de salud y dinero en abundancia');
INSERT INTO "manana" VALUES (11,'Mis pensamientos crean mi realidad');
INSERT INTO "manana" VALUES (12,'Hoy elijo sonreír');
INSERT INTO "manana" VALUES (13,'Aprendo de cada error para continuar mejorando a diario');
INSERT INTO "manana" VALUES (14,'Grandes cosas llegan hoy a mi vida');
INSERT INTO "manana" VALUES (15,'Tengo las habilidades necesarias para resolver los retos que vengan hoy');
INSERT INTO "manana" VALUES (16,'Mi sabiduría interior me ayuda a tomar buenas decisiones');
INSERT INTO "manana" VALUES (17,'Estoy agradecido/a de poder disfrutar de otro día');
INSERT INTO "manana" VALUES (18,'Estoy sano/a y me siento fuerte para empezar el día');
INSERT INTO "manana" VALUES (19,'Me alimento de forma saludable, hago ejercicio con frecuencia y recibo suficiente descanso');
INSERT INTO "manana" VALUES (20,'Aprendo de cada error para continuar mejorando a diario');
INSERT INTO "manana" VALUES (21,'Estoy abierto/a a toda la riqueza que la vida tiene para ofrecer');
INSERT INTO "manana" VALUES (22,'Confío en el universo y en los demás');
INSERT INTO "manana" VALUES (23,'Vivo aquí y ahora');
INSERT INTO "manana" VALUES (24,'Me conozco lo suficiente como para tomar decisiones inteligentes para mí mismo/a');
INSERT INTO "manana" VALUES (25,'Estoy viviendo la vida que deseo');
INSERT INTO "manana" VALUES (26,'Merezco lo mejor y acepto cada regalo');
INSERT INTO "manana" VALUES (27,'Todo está bien, todo está conseguido');
INSERT INTO "manana" VALUES (28,'Cuando soy feliz atraigo a la gente feliz');
INSERT INTO "manana" VALUES (29,'Todo está cambiando y es maravilloso formar parte del cambio');
INSERT INTO "manana" VALUES (30,'Gozo de salud y dinero en abundancia');
INSERT INTO "manana" VALUES (31,'Soy feliz');
INSERT INTO "manana" VALUES (32,'Soy valiosa');
INSERT INTO "manana" VALUES (33,'Soy amada');
INSERT INTO "manana" VALUES (34,'Soy perseverante');
INSERT INTO "manana" VALUES (35,'Soy disciplinada');
INSERT INTO "manana" VALUES (36,'Soy positiva');
INSERT INTO "manana" VALUES (37,'Soy alegre');
INSERT INTO "manana" VALUES (38,'Soy compasiva');
INSERT INTO "manana" VALUES (39,'Soy amorosa');
INSERT INTO "manana" VALUES (40,'Soy sabiduría');
INSERT INTO "manana" VALUES (41,'Soy fuerte');
INSERT INTO "manana" VALUES (42,'Creo en mí');
INSERT INTO "manana" VALUES (43,'Soy exitosa');
INSERT INTO "manana" VALUES (44,'Amo mi trabajo');
INSERT INTO "manana" VALUES (45,'Amo mi cuerpo');
INSERT INTO "manana" VALUES (46,'Amo mi vida');
INSERT INTO "manana" VALUES (47,'Puedo hacerlo');
INSERT INTO "manana" VALUES (48,'Voy a lograrlo');
INSERT INTO "manana" VALUES (49,'Creo en mí');
INSERT INTO "manana" VALUES (50,'Estoy orgullosa de cada paso que doy');
INSERT INTO "manana" VALUES (51,'Hoy decido ser feliz');
INSERT INTO "manana" VALUES (52,'Me acepto incondicionalmente');
INSERT INTO "manana" VALUES (53,'Me amo tal y como soy');
INSERT INTO "manana" VALUES (54,'El Universo conspira a mi favor');
INSERT INTO "manana" VALUES (55,'Mi espíritu es libre y ligero');
INSERT INTO "manana" VALUES (56,'Estoy creando mi vida justo como la soñé');
INSERT INTO "manana" VALUES (57,'Soy un imán para el amor');
INSERT INTO "manana" VALUES (58,'Soy un imán para la fortuna');
INSERT INTO "manana" VALUES (59,'Soy un imán para la prosperidad');
INSERT INTO "manana" VALUES (60,'Soy un imán para las amistades sinceras');
INSERT INTO "manana" VALUES (61,'Estoy tomando mejores decisiones cada día');
INSERT INTO "manana" VALUES (62,'Merezco respeto');
INSERT INTO "manana" VALUES (63,'El éxito es inevitable en mi vida');
INSERT INTO "manana" VALUES (64,'Soy dueña de mi vida');
INSERT INTO "manana" VALUES (65,'Soy un imán de la abundancia');
INSERT INTO "manana" VALUES (66,'Estoy viviendo mi vida soñada');
INSERT INTO "manana" VALUES (67,'Estoy ganando 10,000 dólares al mes');
INSERT INTO "manana" VALUES (68,'Aprendo de mis errores');
INSERT INTO "manana" VALUES (69,'Mi confianza no tiene límites');
INSERT INTO "manana" VALUES (70,'No le temo a los desafíos');
INSERT INTO "manana" VALUES (71,'Soy merecedora de todas las bendiciones que llegan a mi vida');
INSERT INTO "manana" VALUES (72,'Soy más fuerte cada día');
INSERT INTO "manana" VALUES (73,'Tengo el poder de crear la historia de mi vida');
INSERT INTO "manana" VALUES (74,'Tengo confianza en mis habilidades');
INSERT INTO "manana" VALUES (75,'Soy capaz de hacer realidad mis sueños');
INSERT INTO "manana" VALUES (76,'Recibo amor de todos a mi alrededor');
INSERT INTO "manana" VALUES (77,'Amo y disfruto la vida');
INSERT INTO "manana" VALUES (78,'Siento amor y compasión por la humanidad');
INSERT INTO "manana" VALUES (79,'Mis fortalezas me hacen sobresalir');
INSERT INTO "manana" VALUES (80,'Tengo una vida llena de bendiciones');
INSERT INTO "manana" VALUES (81,'Vivo mi presente');
INSERT INTO "manana" VALUES (82,'Atraigo todo lo que deseo');
INSERT INTO "manana" VALUES (83,'Tomo decisiones inteligentes');
INSERT INTO "manana" VALUES (84,'Tengo el poder de crear la vida que deseo');
INSERT INTO "manana" VALUES (85,'Puedo lograr lo que me propongo');
INSERT INTO "manana" VALUES (86,'Puedo ser quien quiera llegar a ser');
INSERT INTO "manana" VALUES (87,'Puedo conseguir todo lo que deseo');
INSERT INTO "manana" VALUES (88,'Encuentro la felicidad en mi propia compañía');
INSERT INTO "manana" VALUES (89,'Estoy agradecida por todo lo que tengo');
INSERT INTO "manana" VALUES (90,'Estoy en el camino correcto para cumplir todas mis metas');
INSERT INTO "manana" VALUES (91,'Soy capaz de ajustarme a cualquier cambio');
INSERT INTO "manana" VALUES (92,'El éxito está en mi futuro');
INSERT INTO "manana" VALUES (93,'No aceptaré aquello que no me hace feliz');
INSERT INTO "manana" VALUES (94,'Puedo alcanzar hasta mis sueños más locos');
INSERT INTO "manana" VALUES (95,'Las críticas no me afectarán');
INSERT INTO "manana" VALUES (96,'No me dejaré para después');
INSERT INTO "manana" VALUES (97,'Mi situación actual no determinará mi destino final');
INSERT INTO "manana" VALUES (98,'No gastaré mi energía en cosas que no aporten a mi vida');
INSERT INTO "manana" VALUES (99,'No me pasaré la vida esperando');
INSERT INTO "manana" VALUES (100,'No tengo que probarle nada a nadie');
INSERT INTO "manana" VALUES (101,'No me quedaré con las ganas');
INSERT INTO "manana" VALUES (102,'Soy capaz de reemplazar cualquier pensamiento negativo con energía positiva');
INSERT INTO "manana" VALUES (103,'Decreto que algo maravilloso está a punto de sucederme');
INSERT INTO "manana" VALUES (104,'Decreto que todos mis sueños pronto se harán realidad');
INSERT INTO "manana" VALUES (105,'Decreto que encontraré el amor en cada aspecto de mi vida');
INSERT INTO "manana" VALUES (106,'Decreto que tendré un día maravilloso');
INSERT INTO "manana" VALUES (107,'Decreto que la vida me sonríe');
INSERT INTO "manana" VALUES (108,'Soy más fuerte de lo que imaginaba');
INSERT INTO "manana" VALUES (109,'Decreto que forjaré mi propio destino');
INSERT INTO "manana" VALUES (110,'Decreto vivir con más esencia y hacerle menos caso a las apariencias');
INSERT INTO "manana" VALUES (111,'Lo sueño, lo busco y lo consigo');
INSERT INTO "manana" VALUES (112,'Mi relación con mi pareja es todo lo que siempre soñé');
INSERT INTO "manana" VALUES (113,'Estoy rodeada de amor');
INSERT INTO "manana" VALUES (114,'Atraigo a mi vida a las personas correctas');
INSERT INTO "manana" VALUES (115,'Veo a mi prójimo con amor');
INSERT INTO "manana" VALUES (116,'Mis acciones positivas se multiplican a mi favor');
INSERT INTO "manana" VALUES (117,'Tengo la vida que siempre soñé');
INSERT INTO "riqueza" VALUES (1,'Estoy rodeada de abundancia.');
INSERT INTO "riqueza" VALUES (2,'Atraigo dinero fácil y sin esfuerzo.');
INSERT INTO "riqueza" VALUES (3,'Estoy abierto a toda la riqueza que la vida tiene para ofrecer.');
INSERT INTO "riqueza" VALUES (4,'Amo al dinero y el dinero me ama.');
INSERT INTO "riqueza" VALUES (5,'Veo abundancia en todas partes.');
INSERT INTO "riqueza" VALUES (6,'Soy financieramente libre y abundante.');
INSERT INTO "riqueza" VALUES (7,'Gran prosperidad está fluyendo hacia mí ahora.');
INSERT INTO "riqueza" VALUES (8,'Atraigo prosperidad donde quiera que vaya.');
INSERT INTO "riqueza" VALUES (9,'La abundancia es mi estado natural y yo lo acepto.');
INSERT INTO "riqueza" VALUES (10,'Permito que la prosperidad y la abundancia de amor entren en mi vida y lo disfruto.');
INSERT INTO "riqueza" VALUES (11,'Siempre se me ocurren ideas que atraen más riqueza.');
INSERT INTO "riqueza" VALUES (12,'Hoy está lleno de oportunidades que aprovecho.');
INSERT INTO "riqueza" VALUES (13,'El universo me proporciona la prosperidad que merezco,');
INSERT INTO "riqueza" VALUES (14,'Veo abundancia en mi vida.');
INSERT INTO "riqueza" VALUES (15,'El dinero que gano me permite contribuir y retribuir al mundo.');
INSERT INTO "riqueza" VALUES (16,'Estoy dispuesta a llevar una vida próspera y feliz.');
INSERT INTO "riqueza" VALUES (17,'Tengo múltiples fuentes de ingreso que crecen cada día.');
INSERT INTO "riqueza" VALUES (18,'Mi vida está llena de prosperidad.');
INSERT INTO "riqueza" VALUES (19,'Mis ingresos se multiplican de formas inesperadas.');
INSERT INTO "riqueza" VALUES (20,'Estoy agradecida con el universo que me proporciona gran prosperidad y riqueza.');
INSERT INTO "riqueza" VALUES (21,'Soy próspera, el dinero fluye hacia mí de muchas fuentes.');
INSERT INTO "riqueza" VALUES (22,'Gracias universo por mi gran prosperidad.');
INSERT INTO "riqueza" VALUES (23,'Cada día soy más y más próspero.');
INSERT INTO "riqueza" VALUES (24,'Suelto toda resistencia a la prosperidad y me llega de forma natural.');
INSERT INTO "riqueza" VALUES (25,'El dinero fluye hacia mí de fuentes esperadas e inesperadas.');
INSERT INTO "riqueza" VALUES (26,'Poseo una mentalidad millonaria.');
INSERT INTO "riqueza" VALUES (27,'La prosperidad apoya mi felicidad.');
INSERT INTO "riqueza" VALUES (28,'El dinero amplifica las oportunidades y experiencias en mi vida.');
INSERT INTO "riqueza" VALUES (29,'El dinero y la prosperidad fluyen libremente en mi vida.');
INSERT INTO "riqueza" VALUES (30,'La prosperidad perfecta es mi realidad elegida.');
INSERT INTO "riqueza" VALUES (31,'Vivo en un universo abundante libre de toda carencia.');
INSERT INTO "riqueza" VALUES (32,'Estoy destinada a encontrar la prosperidad en todo lo que hago.');
INSERT INTO "riqueza" VALUES (33,'Mi energía está alineada con la energía y la vibración de la prosperidad.');
INSERT INTO "riqueza" VALUES (34,'Todo lo que hago me permite ganar más dinero.');
INSERT INTO "riqueza" VALUES (35,'Estoy abierta a la posibilidad de que mis recursos son inagotables e inmediatos.');
INSERT INTO "riqueza" VALUES (36,'Todo lo que hay en el universo, visible o invisible, trabaja para mi prosperidad.');
INSERT INTO "riqueza" VALUES (37,'Mis ingresos financieros son ilimitados.');
INSERT INTO "riqueza" VALUES (38,'Mi cuenta bancaria aumenta cada día.');
INSERT INTO "riqueza" VALUES (39,'El dinero trae alegría y bienestar a mi vida.');
INSERT INTO "riqueza" VALUES (40,'Produzco riqueza económica trabajando en mis pasiones.');
INSERT INTO "riqueza" VALUES (41,'Tengo un suministro infinito de riqueza.');
INSERT INTO "riqueza" VALUES (42,'Me permito tener más de lo que jamás imaginé.');
INSERT INTO "riqueza" VALUES (43,'Cada día en todos los sentidos mi prosperidad va en aumento');
INSERT INTO "riqueza" VALUES (44,'Aprecio y agradezco toda la prosperidad en mi vida.');
INSERT INTO "riqueza" VALUES (45,'Elijo vivir en abundancia y prosperidad.');
INSERT INTO "riqueza" VALUES (46,'Amo al dinero. El dinero me ama');
INSERT INTO "riqueza" VALUES (47,'Siempre tengo ideas para generar dinero');
INSERT INTO "riqueza" VALUES (48,'Estoy recibiendo dinero ahora mismo');
INSERT INTO "riqueza" VALUES (49,'Siento abundancia en todos los aspectos de mi vida');
INSERT INTO "riqueza" VALUES (50,'Tengo más que suficiente dinero');
INSERT INTO "riqueza" VALUES (51,'La riqueza fluye hacia mí en todas las áreas de mi vida. Doy gracias por la capacidad que tengo para atraer riqueza y abundancia');
INSERT INTO "riqueza" VALUES (52,'Mis ingresos son cada vez más y más');
INSERT INTO "riqueza" VALUES (53,'El dinero fluye libremente y en abundancia en mi vida');
INSERT INTO "riqueza" VALUES (54,'Estoy cada vez más magnético al dinero, la prosperidad y la abundancia');
INSERT INTO "riqueza" VALUES (55,'El dinero es una parte integral de mi vida y nunca se encuentra lejos de mí');
INSERT INTO "riqueza" VALUES (56,'Puedo crear dinero y abundancia a través de la alegría, la vitalidad y el amor propio');
INSERT INTO "riqueza" VALUES (57,'Permito que mis ingresos se expandan constantemente y siempre vivo en comunidad y felicidad');
INSERT INTO "riqueza" VALUES (58,'Soy próspero, en mi fluye una corriente inagotable de riqueza');
INSERT INTO "riqueza" VALUES (59,'El éxito financiero es mío y lo acepto ahora mismo');
INSERT INTO "riqueza" VALUES (60,'Hablo de éxito y prosperidad. Mis palabras elevan e inspiran a otros');
INSERT INTO "riqueza" VALUES (61,'Entre más contribuyo hacia los demás, más dinero soy capaz de generar');
INSERT INTO "riqueza" VALUES (62,'Yo vivo una vida abundante, la riqueza vino para quedarse en mi vida');
INSERT INTO "riqueza" VALUES (63,'Estoy atrayendo toda la abundancia que deseo a mi vida fácilmente');
INSERT INTO "riqueza" VALUES (64,'Como puedo hacer lo que me gusta, el dinero y el flujo de la abundancia vienen libremente a mí');
INSERT INTO "riqueza" VALUES (65,'Estoy atrayendo toda la prosperidad financiera');
INSERT INTO "riqueza" VALUES (66,'Me despierto cada mañana emocionada por trabajar en mi pasión y generar riqueza de ella');
INSERT INTO "riqueza" VALUES (67,'Cada día, mi vida está llena de las maravillas y la magia de la abundancia');
INSERT INTO "riqueza" VALUES (68,'Yo fluyo armónicamente con la energía del dinero');
INSERT INTO "riqueza" VALUES (69,'Dejo ir toda resistencia a la prosperidad y viene a mí fácilmente');
INSERT INTO "riqueza" VALUES (70,'Ser rica me da alegría, felicidad y tranquilidad');
INSERT INTO "riqueza" VALUES (71,'Soy abundante y siempre tengo lo suficiente para mí y mi familia');
INSERT INTO "riqueza" VALUES (72,'La riqueza es mi derecho divino, es mi estado natural de ser');
INSERT INTO "riqueza" VALUES (73,'Yo siempre tengo todo lo que necesito');
INSERT INTO "riqueza" VALUES (74,'Me visualizo fácilmente teniendo una abundancia ilimitada');
INSERT INTO "riqueza" VALUES (75,'Declaro abundancia dentro de mí y a mi alrededor');
INSERT INTO "riqueza" VALUES (76,'Soy naturalmente abundante y próspero');
INSERT INTO "riqueza" VALUES (77,'Paso del pensamiento de la pobreza al pensamiento de la prosperidad');
INSERT INTO "riqueza" VALUES (78,'Atraigo sin esfuerzo toda la prosperidad que necesito y deseo');
INSERT INTO "riqueza" VALUES (79,'Libero mi mente de los pensamientos de escases');
INSERT INTO "riqueza" VALUES (80,'Libero toda oposición a la riqueza');
INSERT INTO "riqueza" VALUES (81,'Yo soy ilimitado cuando se trata de dinero, riqueza y prosperidad');
INSERT INTO "riqueza" VALUES (82,'El dinero me encuentra');
INSERT INTO "riqueza" VALUES (83,'Siempre tengo el dinero suficiente para cumplir mis sueños');
INSERT INTO "riqueza" VALUES (84,'Todo dinero que gasto vuelve a mí multiplicado');
INSERT INTO "riqueza" VALUES (85,'Veo venir grandes cantidades de dinero hacia mí');
INSERT INTO "riqueza" VALUES (86,'Nuevas fuentes de ingresos se presentan ante mí');
INSERT INTO "riqueza" VALUES (87,'Dejo ir, en este momento, cualquier creencia negativa acerca del dinero');
INSERT INTO "riqueza" VALUES (88,'Me siento sumamente agradecida por todo lo que tengo');
INSERT INTO "riqueza" VALUES (89,'Merezco ser una persona rica y abundante');
INSERT INTO "riqueza" VALUES (90,'Quiero, puedo, y me lo merezco');
INSERT INTO "riqueza" VALUES (91,'Soy una persona alineada con la energía de la riqueza');
INSERT INTO "riqueza" VALUES (92,'Merezco seguridad financiera y todo lo que trae hacia mí');
INSERT INTO "riqueza" VALUES (93,'Agradezco todo el dinero que está presente en mi vida');
INSERT INTO "riqueza" VALUES (94,'Invierto mi dinero conscientemente');
INSERT INTO "riqueza" VALUES (95,'Soy capaz de crear la vida que deseo');
INSERT INTO "louisehay" VALUES (1,'No es divertido ser una víctima. Rechazo volver a sentirme una persona indefensa.  Reclamo mi fuerza');
INSERT INTO "louisehay" VALUES (2,'Consigo la ayuda que necesito, y ésta puede llegar de cualquier parte. Mi sistema de apoyo es sólido y afectuoso a la vez');
INSERT INTO "louisehay" VALUES (3,'Cuando cometo una equivocación, me doy cuenta que no es más que una parte de mi proceso de aprendizaje');
INSERT INTO "louisehay" VALUES (4,'Mi corazón es el centro de mi poder.  Sigo a mi corazón');
INSERT INTO "louisehay" VALUES (5,'La abundancia fluye libremente a través de mí');
INSERT INTO "louisehay" VALUES (6,'Expreso gratitud por todo el bien de mi vida.  Cada día me aporta maravillosas sorpresas nuevas');
INSERT INTO "louisehay" VALUES (7,'Avanzo en la vida, sé que estoy a salvo y que cuento con la protección y guía Divina');
INSERT INTO "louisehay" VALUES (8,'No importa lo que digan o hagan los demás.  Lo que importa es cómo elijo reaccionar y lo que elijo creer acerca de mí misma');
INSERT INTO "louisehay" VALUES (9,'Elijo sentirme bien respecto a mí mismo. Me merezco mi amor');
INSERT INTO "louisehay" VALUES (10,'El mejor regalo que puedo hacerme es mi amor incondicional');
INSERT INTO "louisehay" VALUES (11,'No es divertido ser una víctima. Rechazo volver a sentirme una persona indefensa. Reclamo mi fuerza');
INSERT INTO "louisehay" VALUES (12,'Consigo la ayuda que necesito, y ésta puede llegar de cualquier parte. Mi sistema de apoyo es sólido y afectuoso a la vez');
INSERT INTO "louisehay" VALUES (13,'Cuando cometo una equivocación, me doy cuenta que no es más que una parte de mi proceso de aprendizaje');
INSERT INTO "louisehay" VALUES (14,'Mi corazón es el centro de mi poder. Sigo a mi corazón');
INSERT INTO "louisehay" VALUES (15,'La abundancia fluye libremente a través de mí');
INSERT INTO "louisehay" VALUES (16,'Expreso gratitud por todo el bien de mi vida. Cada día me aporta maravillosas sorpresas nuevas');
INSERT INTO "louisehay" VALUES (17,'Avanzo en la vida, sé que estoy a salvo y que cuento con la protección y guía Divina');
INSERT INTO "louisehay" VALUES (18,'No importa lo que digan o hagan los demás. Lo que importa es cómo elijo reaccionar y lo que elijo creer acerca de mí misma');
INSERT INTO "louisehay" VALUES (19,'El mejor regalo que puedo hacerme es mi amor incondicional');
INSERT INTO "louisehay" VALUES (20,'Cierro los ojos, tengo pensamientos positivos e inhalo y exhalo bondad');
INSERT INTO "louisehay" VALUES (21,'No importa mi edad, siempre puedo aprender y lo hago con decisión');
INSERT INTO "louisehay" VALUES (22,'Dejo ir toda la negatividad que hay en mi cuerpo y mi mente');
INSERT INTO "louisehay" VALUES (23,'Me deshago de mis temores de la infancia. Me siento segura, soy un ser humano con poder');
INSERT INTO "louisehay" VALUES (24,'Soy una persona capaz y puedo hacer frente a cualquier cosa');
INSERT INTO "louisehay" VALUES (25,'Abandono todo el miedo y la duda; la vida se vuelve sencilla y fácil para mí');
INSERT INTO "louisehay" VALUES (26,'Perdono a todas las personas de mi pasado que me han infligido algún daño.  Las libero con amor');
INSERT INTO "louisehay" VALUES (27,'Sé que no me puedo responsabilizar por otras personas. Todos estamos bajo la ley de nuestra propia conciencia');
INSERT INTO "louisehay" VALUES (28,'Me perdono por no ser una persona perfecta. Vivo de la mejor manera que sé');
INSERT INTO "louisehay" VALUES (29,'La puerta de mi corazón se abre hacia dentro. Paso del rencor al Amor');
INSERT INTO "louisehay" VALUES (30,'El pasado ha terminado, ya no tiene poder en el presente');
INSERT INTO "louisehay" VALUES (31,'No hay problema, ni demasiado grande ni demasiado pequeño, que el amor no pueda resolver');
INSERT INTO "louisehay" VALUES (32,'Paso del perdón a la comprensión y siento compasión por todos');
INSERT INTO "louisehay" VALUES (33,'Soy capaz de perdonar; soy afable, afectuoso y amable, y sé que la vida me ama');
INSERT INTO "louisehay" VALUES (34,'Me libero en este momento de todos los traumas de mi infancia y vivo en el amor');
INSERT INTO "louisehay" VALUES (35,'Todas las personas tienen algo que enseñarme.  Hay un propósito para que estemos juntos');
INSERT INTO "louisehay" VALUES (36,'Todos los cambios que tengo ante mí en la vida son positivos');
INSERT INTO "louisehay" VALUES (37,'Cada día me ofrece una nueva oportunidad.  El ayer ya ha concluido. Hoy es el primer día de mi futuro');
INSERT INTO "louisehay" VALUES (38,'No puedo cambiar a otras personas. Dejo a los demás ser como son y simplemente me amo tal como soy');
INSERT INTO "louisehay" VALUES (39,'Me siento seguro cuando expreso mis sentimientos. Puedo estar sereno en cualquier situación');
INSERT INTO "louisehay" VALUES (40,'Estoy en el lugar correcto, en el momento adecuado, haciendo lo correcto');
INSERT INTO "louisehay" VALUES (41,'Cada pensamiento que pensamos está creando nuestro futuro');
INSERT INTO "louisehay" VALUES (42,'Recuerda, te has estado criticando durante años y no ha funcionado. Intenta aprobarte y ver qué pasa');
INSERT INTO "louisehay" VALUES (43,'El amor es la gran cura milagrosa. Amarnos a nosotros mismos hace milagros en nuestras vidas');
INSERT INTO "louisehay" VALUES (44,'No soluciono problemas. Arreglo mi pensamiento. Entonces los problemas se solucionan solos');
INSERT INTO "louisehay" VALUES (45,'Me he dado cuenta de que el Universo ama la Gratitud. Cuanto más agradecido estés, más golosinas obtendrás');
INSERT INTO "louisehay" VALUES (46,'Estoy dispuesto a liberar la necesidad de ser indigno. Soy digno de lo mejor en la vida, y ahora con amor me permito aceptarlo');
INSERT INTO "louisehay" VALUES (47,'No importa dónde vivamos en el planeta o lo difícil que parezca nuestra situación, tenemos la capacidad de superar y trascender nuestras circunstancias');
INSERT INTO "louisehay" VALUES (48,'En el centro de mi ser hay un pozo infinito de amor');
INSERT INTO "louisehay" VALUES (49,'Todo está bien. Todo está funcionando para mi mayor bien. Fuera de esta situación solo vendrá la buena voluntad. Estoy a salvo');
INSERT INTO "louisehay" VALUES (50,'Algunas personas prefieren dejar el planeta que cambiar');
INSERT INTO "louisehay" VALUES (51,'Abandono todo el miedo y la duda; la vida se vuelve sencilla y fácil para mí');
INSERT INTO "louisehay" VALUES (52,'El humor y la alegría contribuyen a mi bienestar general');
INSERT INTO "louisehay" VALUES (53,'Cuando me equivoco, me doy cuenta que no es más que una parte de mi proceso de aprendizaje');
INSERT INTO "louisehay" VALUES (54,'Soy una persona capaz y puedo hacer frente a cualquier cosa');
INSERT INTO "louisehay" VALUES (55,'No hay problema, ni demasiado grande ni demasiado pequeño, que el amor no pueda resolver');
INSERT INTO "louisehay" VALUES (56,'Recuerda, en la gran infinidad de la vida, todo es perfecto, entero y completo, y también lo eres tú');
INSERT INTO "louisehay" VALUES (57,'Sé que los viejos patrones negativos ya no me limitan. Me despojo de ellos sin esfuerzo');
INSERT INTO "louisehay" VALUES (58,'Aprende del pasado y déjalo ir. Vive en el presente');
INSERT INTO "louisehay" VALUES (59,'Hoy escucho mis sentimientos y soy amable conmigo mismo. Sé que todos mis sentimientos son mis amigos');
INSERT INTO "louisehay" VALUES (60,'Todos los cambios que tengo ante mí en la vida son positivos');
INSERT INTO "louisehay" VALUES (61,'Cada día es una nueva oportunidad. Elijo hacer de este un gran día');
INSERT INTO "amorpropio" VALUES (1,'Todo lo que busco lo encuentro dentro de mí.');
INSERT INTO "amorpropio" VALUES (2,'Merezco amar y ser amada.');
INSERT INTO "amorpropio" VALUES (3,'Me acepto y me amo incondicionalmente.');
INSERT INTO "amorpropio" VALUES (4,'El amor propio es mi prioridad intencional.');
INSERT INTO "amorpropio" VALUES (5,'Amo el cuerpo que mi alma ha elegido para habitar y vivir.');
INSERT INTO "amorpropio" VALUES (6,'Estoy dispuesta a cuidar mi cuerpo, mi alma, mi mente y mis emociones.');
INSERT INTO "amorpropio" VALUES (7,'Irradio confianza.');
INSERT INTO "amorpropio" VALUES (8,'Soy mi lugar seguro y lleno de amor.');
INSERT INTO "amorpropio" VALUES (9,'Decido darme lo mejor y apreciarme más cada día.');
INSERT INTO "amorpropio" VALUES (10,'Acepto y reconozco la divinidad en mí.');
INSERT INTO "amorpropio" VALUES (11,'Practico el autocuidado personal y me amo.');
INSERT INTO "amorpropio" VALUES (12,'Soy merecedora de todo lo bueno que la vida me puede ofrecer.');
INSERT INTO "amorpropio" VALUES (13,'Tengo el poder de co-crear la vida que amo.');
INSERT INTO "amorpropio" VALUES (14,'Me siento cómoda en mi cuerpo.');
INSERT INTO "amorpropio" VALUES (15,'El amor fluye a través de mí.');
INSERT INTO "amorpropio" VALUES (16,'Creo y confío en mí.');
INSERT INTO "amorpropio" VALUES (17,'Amo mi cuerpo y lo respeto.');
INSERT INTO "amorpropio" VALUES (18,'Mi cuerpo es mi mejor amigo.');
INSERT INTO "amorpropio" VALUES (19,'Envío amor y salud a cada parte de mi cuerpo.');
INSERT INTO "amorpropio" VALUES (20,'Soy única, maravillosa y auténtica.');
INSERT INTO "amorpropio" VALUES (21,'Mi vida y mi felicidad son importantes.');
INSERT INTO "amorpropio" VALUES (22,'Entiendo que mis sueños y aspiraciones son mi responsabilidad.');
INSERT INTO "amorpropio" VALUES (23,'Avanzo con la frente en alto, feliz de ser quien soy.');
INSERT INTO "amorpropio" VALUES (24,'Me siento orgullosa de la persona que veo al mirarme al espejo.');
INSERT INTO "amorpropio" VALUES (25,'Confío en mi intuición y respeto mi voz interior.');
INSERT INTO "amorpropio" VALUES (26,'Amo cada parte de mí.');
INSERT INTO "amorpropio" VALUES (27,'Añado valor al mundo y tengo un propósito maravilloso.');
INSERT INTO "amorpropio" VALUES (28,'Escucho y respeto mi cuerpo y disfruto de buena salud.');
INSERT INTO "amorpropio" VALUES (29,'Me acepto y me amo tal como soy mientras trabajo en mi desarrollo continuo y cuidado personal.');
INSERT INTO "amorpropio" VALUES (30,'Aprecio el sinérgico trabajo que cada parte de mi cuerpo realiza día tras día.');
INSERT INTO "amorpropio" VALUES (31,'Merezco lo mejor y acepto lo mejor ahora');
INSERT INTO "amorpropio" VALUES (32,'Me abro a la belleza de la vida');
INSERT INTO "amorpropio" VALUES (33,'Presto atención a mi pensamiento y elijo conscientemente pensamientos saludables');
INSERT INTO "amorpropio" VALUES (34,'Acepto el desafío de mejorar como persona');
INSERT INTO "amorpropio" VALUES (35,'Confío en la vida y ella me responde de la misma manera');
INSERT INTO "amorpropio" VALUES (36,'Me alimento de forma saludable, hago ejercicio con frecuencia y recibo suficiente descanso');
INSERT INTO "amorpropio" VALUES (37,'La energía positiva fluye dentro de mi');
INSERT INTO "amorpropio" VALUES (38,'Decreto que algo maravilloso está a punto de sucederme');
INSERT INTO "amorpropio" VALUES (39,'Puedo alcanzar hasta mis sueños más locos');
INSERT INTO "amorpropio" VALUES (40,'El éxito es inevitable en mi vida');
INSERT INTO "amorpropio" VALUES (41,'Le doy la bienvenida a nuevas ideas y puntos de vista');
INSERT INTO "amorpropio" VALUES (42,'Gracias porque cada día y en todos los sentidos estoy mejor, mejor y mejor');
INSERT INTO "amorpropio" VALUES (43,'La vida y el universo están de mi parte, me apoyan totalmente y me proporcionan todo lo que necesito');
INSERT INTO "amorpropio" VALUES (44,'Estoy a cargo, ahora recupero mi propio poder');
INSERT INTO "amorpropio" VALUES (45,'Mis intuiciones son acertadas, estoy enfocado a las cosas que deseo y que son positivas para mi');
INSERT INTO "amorpropio" VALUES (46,'He renunciado a toda la programación mental negativa que condicionaba mis decisiones');
INSERT INTO "amorpropio" VALUES (47,'Doy lo mejor de mi en cada situación');
INSERT INTO "amorpropio" VALUES (48,'Escucho mis sensaciones y soy amable conmigo mismo');
INSERT INTO "amorpropio" VALUES (49,'Me divierto haciendo lo que hago en mi día a día');
INSERT INTO "amorpropio" VALUES (50,'Dejo ir todos mis miedos y dudas');
INSERT INTO "amorpropio" VALUES (51,'La vida se vuelve sencilla y amorosa para mi');
INSERT INTO "amorpropio" VALUES (52,'Soy la energía que quiero atraer');
INSERT INTO "amorpropio" VALUES (53,'Soy belleza y nadie puede convencerme de lo contrario');
INSERT INTO "amorpropio" VALUES (54,'Me amo y estoy orgullosa de lo que he logrado');
INSERT INTO "amorpropio" VALUES (55,'Tengo el poder de crear la vida que deseo');
INSERT INTO "amorpropio" VALUES (56,'Me siento muy feliz y cómoda siendo yo misma');
INSERT INTO "amorpropio" VALUES (57,'Reconozco mis talentos, mis cualidades y mi belleza');
INSERT INTO "amorpropio" VALUES (58,'Me estoy enamorando de mi');
INSERT INTO "amorpropio" VALUES (59,'Me amo incondicionalmente y me acepto tal y como soy');
INSERT INTO "amorpropio" VALUES (60,'Elijo dejar de disculparme por ser yo misma');
INSERT INTO "amorpropio" VALUES (61,'Yo irradio confianza y armonía interior');
INSERT INTO "amorpropio" VALUES (62,'Soy la energía que quiero atraer');
INSERT INTO "amorpropio" VALUES (63,'Soy belleza y nadie puede convencerme de lo contrario');
INSERT INTO "amorpropio" VALUES (64,'Me amo y estoy orgullosa de lo que he logrado');
INSERT INTO "amorpropio" VALUES (65,'Tengo el poder de crear la vida que deseo');
INSERT INTO "amorpropio" VALUES (66,'Me siento muy feliz y cómoda siendo yo misma');
INSERT INTO "amorpropio" VALUES (67,'Reconozco mis talentos, mis cualidades y mi belleza');
INSERT INTO "amorpropio" VALUES (68,'Me estoy enamorando de mi');
INSERT INTO "amorpropio" VALUES (69,'Me amo incondicionalmente y me acepto tal y como soy');
INSERT INTO "amorpropio" VALUES (70,'Elijo dejar de disculparme por ser yo misma');
INSERT INTO "amorpropio" VALUES (71,'Yo irradio confianza y armonía interior');
INSERT INTO "amorpropio" VALUES (72,'Amo a mi cuerpo y todo lo que hace por mi');
INSERT INTO "amorpropio" VALUES (73,'Hoy elijo ver la perfección divina que reside en cada célula de mi cuerpo');
INSERT INTO "amorpropio" VALUES (74,'Soy talentosa y aprendo cada día nuevas formas de apreciarme');
INSERT INTO "amorpropio" VALUES (75,'Yo tengo confianza en mis capacidades y en mi criterio y se que puedo lograr cualquier cosa');
INSERT INTO "amorpropio" VALUES (76,'Soy merecedora del amor en todas sus formas y expresiones');
INSERT INTO "amorpropio" VALUES (77,'Me doy permiso de enfocarme en lo que me gusta de mí misma');
INSERT INTO "amorpropio" VALUES (78,'Supero las creencias negativas que tengo sobre mí');
INSERT INTO "amorpropio" VALUES (79,'Me deshago de mis miedos y me permito confiar en mi cuerpo');
INSERT INTO "amorpropio" VALUES (80,'Mi belleza interior se refleja en cada parte de mi cuerpo y personalidad');
INSERT INTO "amorpropio" VALUES (81,'Entre más me amo de manera incondicional, más amor llega a mi vida');
INSERT INTO "amor" VALUES (1,'Solo atraigo personas confiables y positivas.');
INSERT INTO "amor" VALUES (2,'Doy y recibo amor por igual.');
INSERT INTO "amor" VALUES (3,'Abro mi corazón al amor y a la vida.');
INSERT INTO "amor" VALUES (4,'Tengo abundancia de amor para dar.');
INSERT INTO "amor" VALUES (5,'Cuanto más me amo más amor siento por los demás.');
INSERT INTO "amor" VALUES (6,'Expreso mis deseos y necesidades de manera clara y asertiva.');
INSERT INTO "amor" VALUES (7,'El amor trae energía y alegría a mi vida.');
INSERT INTO "amor" VALUES (8,'Mis relaciones están llenas de respeto, comprensión y amor.');
INSERT INTO "amor" VALUES (9,'Soy una persona valiosa y me amo.');
INSERT INTO "amor" VALUES (10,'Tengo lazos cercanos y saludables con mi pareja.');
INSERT INTO "amor" VALUES (11,'En mis relaciones hay amor y comprensión.');
INSERT INTO "amor" VALUES (12,'Amo incondicionalmente y sin dudarlo.');
INSERT INTO "amor" VALUES (13,'Amo con aceptación y libertad.');
INSERT INTO "amor" VALUES (14,'Vibro en la frecuencia del amor más auténtico.');
INSERT INTO "amor" VALUES (15,'Todas mis relaciones son armoniosas.');
INSERT INTO "amor" VALUES (16,'Donde quiera que voy, estoy acompañado de amor.');
INSERT INTO "amor" VALUES (17,'El amor verdadero llega a mi vida para quedarse.');
INSERT INTO "amor" VALUES (18,'Mi matrimonio (o relación) es más fuerte, más profunda y más amorosa cada día.');
INSERT INTO "amor" VALUES (19,'Mantengo relaciones saludables y plenas con mi pareja y amigos.');
INSERT INTO "amor" VALUES (20,'Doy gracias a la vida por darme la capacidad de amar y ser amada.');
INSERT INTO "amor" VALUES (21,'Mi vida es maravillosa, amo a mi familia y ellos me aman a mí.');
INSERT INTO "amor" VALUES (22,'Doy gracias a la vida por darme la capacidad de amar y ser amado');
INSERT INTO "amor" VALUES (23,'El amor de mi vida está viniendo hacia mí en este momento');
INSERT INTO "amor" VALUES (24,'El amor de mi corazón inunda alegremente todo mi cuerpo');
INSERT INTO "amor" VALUES (25,'Me amo y disfruto conmigo misma');
INSERT INTO "amor" VALUES (26,'Mi corazón está abierto.  Estoy dispuesta a abandonar toda resistencia');
INSERT INTO "amor" VALUES (27,'Me amo a mi mismo exactamente como soy ahora mismo');
INSERT INTO "amor" VALUES (28,'Desarrollo conexiones profundas con quienes me rodean');
INSERT INTO "amor" VALUES (29,'Mi luz interior atrae amor');
INSERT INTO "amor" VALUES (30,'Me siento a gusto con todas las personas que conozco. Todas mis relaciones son sanas y alentadoras');
INSERT INTO "amor" VALUES (31,'Merezco disfrutar la vida. Pido lo que merezco y lo acepto con placer y alegría');
INSERT INTO "amor" VALUES (32,'Mi vida está llena de amor');
INSERT INTO "amor" VALUES (33,'Tengo abundancia de amor para dar');
INSERT INTO "amor" VALUES (34,'Atraigo todo romanticismo a mi vida');
INSERT INTO "amor" VALUES (35,'Permito que el amor me encuentre. Estoy determinado a atraerlo hacia mí');
INSERT INTO "amor" VALUES (36,'Respiro amor, siento amor');
INSERT INTO "amor" VALUES (37,'Te observo claramente con los ojos del amor y me encanta lo que veo');
INSERT INTO "amor" VALUES (38,'Doy y recibo amor con pasión y ternura');
INSERT INTO "amor" VALUES (39,'El amor lo puede todo');
INSERT INTO "amor" VALUES (40,'Soy merecedor de tener a mi lado al amor de mi vida');
INSERT INTO "amor" VALUES (41,'Estoy en proceso de atraer hacia mí a mi alma gemela');
INSERT INTO "amor" VALUES (42,'Doy gracias al destino por ser capaz de amar y ser amado incondicionalmente');
INSERT INTO "amor" VALUES (43,'A quién busco, también me busca a mí, estamos unidos por el infinito');
INSERT INTO "amor" VALUES (44,'Abro las puertas a un amor sano y verdadero');
INSERT INTO "amor" VALUES (45,'Siento inmensa gratitud por tener a mi compañero/a ideal a mi lado');
INSERT INTO "amor" VALUES (46,'Yo merezco amor, romance, felicidad, y todo lo bueno que la vida tiene para ofrecerme');
INSERT INTO "amor" VALUES (47,'Tengo una pareja que me ama y me acepta tal como soy');
INSERT INTO "amor" VALUES (48,'Sé reconocer a la persona indicada para establecer la relación que quiero');
INSERT INTO "amor" VALUES (49,'El amor llega a mi vida trayendo inmensas satisfacciones');
INSERT INTO "amor" VALUES (50,'Agradezco las relaciones que he tenido porque me han preparado para este momento perfecto');
INSERT INTO "amor" VALUES (51,'Soy libre cuando estoy solo/a y cuando estoy en pareja');
INSERT INTO "atencion" VALUES (1,'Vivo mi presente con entusiasmo.');
INSERT INTO "atencion" VALUES (2,'Vivo aquí y ahora y lo disfruto plenamente.');
INSERT INTO "atencion" VALUES (3,'Me permito disfrutar al máximo cada experiencia que vivo en el presente.');
INSERT INTO "atencion" VALUES (4,'Mi mente está en paz.');
INSERT INTO "atencion" VALUES (5,'Disfruto este momento único e irrepetible de mi vida..');
INSERT INTO "atencion" VALUES (6,'Vivo en el presente y tengo confianza en el futuro.');
INSERT INTO "atencion" VALUES (7,'Me doy permiso de experimentar al máximo mi presente, mi ahora.');
INSERT INTO "atencion" VALUES (8,'Todo está bien en mi mundo. Vivo feliz y en armonía.');
INSERT INTO "atencion" VALUES (9,'Dejo ir el pasado y disfruto plenamente el presente.');
INSERT INTO "atencion" VALUES (10,'Estoy emocionado de ver lo que depara el día de hoy.');
INSERT INTO "atencion" VALUES (11,'Ahora me siento feliz.');
INSERT INTO "atencion" VALUES (12,'Saboreo las experiencias que vivo en este momento.');
INSERT INTO "atencion" VALUES (13,'Mi mente y mi corazón están conectados y alineados con el momento presente.');
INSERT INTO "atencion" VALUES (14,'Mis días están llenos de bendiciones cada minuto.');
INSERT INTO "atencion" VALUES (15,'Estoy dispuesta a disfrutar y saborear más el momento presente.');
INSERT INTO "atencion" VALUES (16,'Me siento maravillosamente tranquilo y relajado.');
INSERT INTO "atencion" VALUES (17,'Me siento feliz y me siento amada, aquí y ahora.');
INSERT INTO "atencion" VALUES (18,'Estoy en conexión plena con este momento que vivo.');
INSERT INTO "mente" VALUES (1,'Alcanzo las metas que me propongo.');
INSERT INTO "mente" VALUES (2,'Todos los días en todo lo que hago estoy mejor, mejor y mejor.');
INSERT INTO "mente" VALUES (3,'Tengo suficientes recursos personales para lograr éxito en mi vida.');
INSERT INTO "mente" VALUES (4,'Estoy en paz con el que mundo que me rodea y el mundo está en paz conmigo.');
INSERT INTO "mente" VALUES (5,'En mi vida siempre hay abundancia de recursos.');
INSERT INTO "mente" VALUES (6,'Encuentro felicidad y placer en las cosas más simples de la vida.');
INSERT INTO "mente" VALUES (7,'Mi mente está preparada para aprender cosas nuevas.');
INSERT INTO "mente" VALUES (8,'Puedo alcanzar la grandeza mientras desarrollo mi potencial.');
INSERT INTO "mente" VALUES (9,'Mi potencial para tener éxito es infinito.');
INSERT INTO "mente" VALUES (10,'Elijo saborear cada segundo de mi vida.');
INSERT INTO "mente" VALUES (11,'Hoy todas las puertas se abren para mí.');
INSERT INTO "mente" VALUES (12,'Soy creativo y lleno de ideas brillantes.');
INSERT INTO "mente" VALUES (13,'Tengo la capacidad de crear y lograr lo que deseo.');
INSERT INTO "mente" VALUES (14,'Soy el creador de mi realidad.');
INSERT INTO "mente" VALUES (15,'La vida es fácil y divertida.');
INSERT INTO "mente" VALUES (16,'Todo funciona para mi mayor bien.');
INSERT INTO "mente" VALUES (17,'Soy un ser espiritual que tiene una experiencia física.');
INSERT INTO "mente" VALUES (18,'Merezco una vida abundante, llena de amor y felicidad.');
INSERT INTO "mente" VALUES (19,'Todo llega a mi vida con facilidad, gozo y gloria.');
INSERT INTO "mente" VALUES (20,'Estoy abierta a cambiar de actitud y vivir feliz.');
INSERT INTO "mente" VALUES (21,'Maravillosas sorpresas llegan todos los días a mí.');
INSERT INTO "mente" VALUES (22,'Merezco que sucedan cosas maravillosas en mi vida.');
INSERT INTO "mente" VALUES (23,'Recibo con amor y alegría los momentos maravillosos que fluyen a mí constantemente.');
INSERT INTO "mente" VALUES (24,'Siempre tengo todo lo que necesito.');
INSERT INTO "mente" VALUES (25,'Tengo la capacidad de crear y lograr lo que deseo.');
INSERT INTO "mente" VALUES (26,'Soy amado y apoyado por el universo.');
INSERT INTO "mente" VALUES (27,'Estoy dispuesta a desaprender antiguos patrones.');
INSERT INTO "mente" VALUES (28,'Confío en que soy guiada para dar resultados maravillosos y sorprendentes.');
INSERT INTO "mente" VALUES (29,'Recibo y doy amor ilimitado.');
INSERT INTO "mente" VALUES (30,'Disfruto de mi energía y mi buena actitud.');
INSERT INTO "mente" VALUES (31,'Elijo vivir con paz en mi interior.');
INSERT INTO "mente" VALUES (32,'Hoy es un día lleno de oportunidades y abro mi corazón para recibirlas.');
INSERT INTO "mente" VALUES (33,'Doy las gracias por el flujo ilimitado de cosas buenas en mi vida.');
INSERT INTO "mente" VALUES (34,'Estoy eternamente agradecido por el amor que soy capaz de dar y por el amor que aún tengo que recibir');
INSERT INTO "mente" VALUES (35,'Hoy me espera un excelente día y lo voy a disfrutar al máximo');
INSERT INTO "mente" VALUES (36,'Pase lo que pase, estoy seguro de que puedo volver a estar agradecido');
INSERT INTO "mente" VALUES (37,'Gracias por que tengo a mi familia, a mis seres queridos y a mis amigos');
INSERT INTO "mente" VALUES (38,'Estoy agradecido ahora, y eso es mantener la puerta abierta para recibir más bendiciones');
INSERT INTO "mente" VALUES (39,'Doy la bienvenida a todas las formas en que el universo quiere bendecirme');
INSERT INTO "mente" VALUES (40,'Gracias porque todo mi cuerpo está sano, fuerte y con energía suficiente');
INSERT INTO "mente" VALUES (41,'Confío en que el universo está apoyando mi mayor bien');
INSERT INTO "mente" VALUES (42,'Gracias porque estoy en el lugar perfecto y en el momento oportuno, haciendo lo adecuado');
INSERT INTO "mente" VALUES (43,'El sentimiento de agradecimiento amplía mi perspectiva y me abre a nuevas formas de vivir feliz en este mundo; es como si todo el universo estuviera en mi corazón');
INSERT INTO "mente" VALUES (44,'Estoy eternamente agradecido por el amor que soy capaz de dar y por el amor que aún tengo que recibir');
INSERT INTO "mente" VALUES (45,'Hoy me espera un excelente día y lo voy a disfrutar al máximo');
INSERT INTO "mente" VALUES (46,'Pase lo que pase, estoy seguro de que puedo volver a estar agradecido');
INSERT INTO "mente" VALUES (47,'Gracias por que tengo a mi familia, a mis seres queridos y a mis amigos');
INSERT INTO "mente" VALUES (48,'Estoy agradecido ahora, y eso es mantener la puerta abierta para recibir más bendiciones');
INSERT INTO "mente" VALUES (49,'Doy la bienvenida a todas las formas en que el universo quiere bendecirme');
INSERT INTO "mente" VALUES (50,'Gracias porque todo mi cuerpo está sano, fuerte y con energía suficiente');
INSERT INTO "mente" VALUES (51,'Confío en que el universo está apoyando mi mayor bien');
INSERT INTO "mente" VALUES (52,'Gracias porque estoy en el lugar perfecto y en el momento oportuno, haciendo lo adecuado');
INSERT INTO "mente" VALUES (53,'El sentimiento de agradecimiento amplía mi perspectiva y me abre a nuevas formas de vivir feliz en este mundo; es como si todo el universo estuviera en mi corazón');
INSERT INTO "mente" VALUES (54,'Mi acción de gracias se extiende mucho más allá de mis pensamientos; aporto un espíritu agradecido a cada paso y acción que doy');
INSERT INTO "mente" VALUES (55,'Gracias porque todas mis relaciones son armoniosas');
INSERT INTO "mente" VALUES (56,'Hago brillar la luz del aprecio sobre una situación que de otro modo sería oscura; no hay oscuridad que pueda escapar de esa luz por mucho tiempo');
INSERT INTO "mente" VALUES (57,'Gracias porque me siento bien con todas las personas');
INSERT INTO "mente" VALUES (58,'Hoy me asocio con la paz y lo hago a través del poder de mantener un corazón agradecido');
INSERT INTO "mente" VALUES (59,'Gracias por toda la abundancia y prosperidad que hay en mi vida');
INSERT INTO "mente" VALUES (60,'Gracias por todo lo que soy y todo lo que tengo');
INSERT INTO "mente" VALUES (61,'En cambio, elijo ver la paz');
INSERT INTO "mente" VALUES (62,'Vivo todos los momentos de mi vida con amplia gratitud');
INSERT INTO "mente" VALUES (63,'La gratitud es un hábito que cultivo diariamente');
INSERT INTO "mente" VALUES (64,'Acepto agradecidamente los regalos que me da la vida');
INSERT INTO "mente" VALUES (65,'Estoy agradecida porque tengo un techo donde refugiarme');
INSERT INTO "mente" VALUES (66,'Hoy agradezco las lecciones y el aprendizaje que la vida me da');
INSERT INTO "mente" VALUES (67,'Doy gracias por mi vida y salud diariamente');
INSERT INTO "mente" VALUES (68,'Gracias por otra oportunidad de ser mejor que ayer');
INSERT INTO "mente" VALUES (69,'Doy gracias por este bello día');
INSERT INTO "mente" VALUES (70,'Vivo en un universo lleno de abundancia, y agradezco por ello');
INSERT INTO "mente" VALUES (71,'Hoy agradezco los bienes que poseo y las bendiciones que recibo cada día');
INSERT INTO "mente" VALUES (72,'Agradezco profundamente a mi cuerpo y a mi mente por todo el trabajo que han hecho hoy');
INSERT INTO "mente" VALUES (73,'Siento gratitud por toda mi existencia');
INSERT INTO "mente" VALUES (74,'Elijo ver esta temporada de mi vida, entonces, a través de los ojos del aprecio, lo mejor que pueda');
INSERT INTO "mente" VALUES (75,'Estoy dispuesto a confiar en que mi vida es exactamente como debe ser');
INSERT INTO "mente" VALUES (76,'Puedo relajarme un poco y estar agradecido por lo que tengo ahora');
INSERT INTO "negocio" VALUES (1,'Genero riqueza económica con todo lo que hago.');
INSERT INTO "negocio" VALUES (2,'Estoy en el proceso de construir un negocio exitoso.');
INSERT INTO "negocio" VALUES (3,'Mi ambiente de trabajo es tranquilo y relajado.');
INSERT INTO "negocio" VALUES (4,'Vender es algo natural en mí.');
INSERT INTO "negocio" VALUES (5,'Mi negocio es un lugar tranquilo, amoroso y lleno de gente maravillosa y talentosa.');
INSERT INTO "negocio" VALUES (6,'A través de mi negocio hago una gran diferencia en este mundo.');
INSERT INTO "negocio" VALUES (7,'Me siento feliz en mi negocio y mi trabajo.');
INSERT INTO "negocio" VALUES (8,'Cada día nuevos clientes solicitan mis productos o servicios.');
INSERT INTO "negocio" VALUES (9,'Estoy feliz y agradecida porque mi negocio se fortalece y crece todos los días.');
INSERT INTO "negocio" VALUES (10,'Mi trabajo me permite expresar mis talentos y habilidades.');
INSERT INTO "negocio" VALUES (11,'Agradezco los cambios como oportunidades para avanzar y progresar.');
INSERT INTO "negocio" VALUES (12,'Cada desafío, dificultad o fracaso me han convertido en un mejor hombre(o mujer) de negocios.');
INSERT INTO "negocio" VALUES (13,'Vivo un excelente año y atraigo las mejores opciones para mí.');
INSERT INTO "negocio" VALUES (14,'Cada día nuevas y mejores oportunidades se presentan a mi puerta.');
INSERT INTO "negocio" VALUES (15,'Doy lo mejor de mi en mi negocio.');
INSERT INTO "negocio" VALUES (16,'Elijo los caminos más convenientes y prósperos para mi empresa.');
INSERT INTO "negocio" VALUES (17,'Mis ingresos se multiplican exponencialmente cada día.');
INSERT INTO "negocio" VALUES (18,'Estoy abierta a ser una profesional reconocida, famosa y muy solicitada.');
INSERT INTO "negocio" VALUES (19,'Mi emprendimiento se expande y crece más cada día.');
INSERT INTO "negocio" VALUES (20,'Soy creativa, ingeniosa y persuasiva y vendo con entusiasmo mis ideas y proyectos.');
INSERT INTO "negocio" VALUES (21,'Soy excelente en todo lo que hago y genero abundantes ganancias con mis proyectos.');
INSERT INTO "negocio" VALUES (22,'Tengo las habilidades y el conocimiento para tomar las mejores decisiones para mi carrera');
INSERT INTO "negocio" VALUES (23,'Estoy enfocado y apasionado por mis objetivos y mi carrera');
INSERT INTO "negocio" VALUES (24,'Tengo el impulso y la ambición para lograr mis objetivos');
INSERT INTO "negocio" VALUES (25,'Me permito crecer y aprender');
INSERT INTO "negocio" VALUES (26,'Confío en mis habilidades para alcanzar la cima de mi profesión');
INSERT INTO "negocio" VALUES (27,'No importa dónde esté, solo hay un bien infinito, una sabiduría infinita, una armonía y un amor infinitos');
INSERT INTO "negocio" VALUES (28,'Mi alegría me permite expresar mis talentos y habilidades, y estoy agradecida por este empleo');
INSERT INTO "negocio" VALUES (29,'En mi trabajo, mis compañeros de trabajo y yo fomentamos el crecimiento y el éxito de los demás');
INSERT INTO "negocio" VALUES (30,'Cuando me despierto por la mañana, planeo un buen día');
INSERT INTO "negocio" VALUES (31,'Realmente creo que nosotros estamos aquí para bendecirnos el uno al otro');
INSERT INTO "negocio" VALUES (32,'Tengo facilidad para hablar frente a otros');
INSERT INTO "negocio" VALUES (33,'Cuando me encuentro con problemas en el trabajo, estoy dispuesta a solicitar ayuda');
INSERT INTO "negocio" VALUES (34,'Creo un buen sentimiento en el trabajo');
INSERT INTO "negocio" VALUES (35,'Sé que cuando hago lo mejor en mi trabajo, me recompensan de todas las formas');
INSERT INTO "negocio" VALUES (36,'Avanzo fácil y rápidamente en la realización de mis trabajos');
INSERT INTO "negocio" VALUES (37,'Soy una persona muy eficiente en todo lo que hago');
INSERT INTO "negocio" VALUES (38,'Trabajo en un lugar armonioso, con buen horario y bien pagado');
INSERT INTO "negocio" VALUES (39,'Aprendo a diario mejores estrategias');
INSERT INTO "negocio" VALUES (40,'Me siento orgulloso del éxito en mi trabajo');
INSERT INTO "negocio" VALUES (41,'Agradezco verme como una persona exitosa y satisfecha');
INSERT INTO "negocio" VALUES (42,'Agradezco la vida maravillosa y los gustos que me puedo dar a mí y a mis seres queridos gracias a la excelente remuneración que recibo por mi trabajo');
INSERT INTO "negocio" VALUES (43,'Agradezco por tener las mejores capacidades para desempeñar el empleo que tanto me gusta');
INSERT INTO "negocio" VALUES (44,'Tengo todas las habilidades y conocimientos para cumplir con el trabajo de mis sueños');
INSERT INTO "negocio" VALUES (45,'Soy el candidato perfecto para este puesto');
INSERT INTO "negocio" VALUES (46,'Decreto que soy feliz y que el empleo que tengo es perfecto para mí, porque ahora el dinero me pertenece y me llega en abundancia');
INSERT INTO "negocio" VALUES (47,'Tengo la seguridad de que voy a conseguir un mejor empleo con éxito y felicidad');
INSERT INTO "negocio" VALUES (48,'Agradezco el ambiente laboral en el que me muevo');
INSERT INTO "negocio" VALUES (49,'Tengo confianza en mí mismo');
INSERT INTO "negocio" VALUES (50,'Abro mi corazón para recibir esta energía maravillosa de abundancia y seguridad que atrae el trabajo de mis sueños ahora');
INSERT INTO "negocio" VALUES (51,'Atraigo todo lo necesario para lograr mis metas laborales');
INSERT INTO "negocio" VALUES (52,'Tengo las habilidades y el conocimiento para tomar las mejores decisiones para mi carrera');
INSERT INTO "negocio" VALUES (53,'Estoy enfocado y apasionado por mis objetivos y mi carrera');
INSERT INTO "negocio" VALUES (54,'Tengo el impulso y la ambición para lograr mis objetivos');
INSERT INTO "negocio" VALUES (55,'Me permito crecer y aprender');
INSERT INTO "negocio" VALUES (56,'Confío en mis habilidades para alcanzar la cima de mi profesión');
INSERT INTO "negocio" VALUES (57,'No importa dónde esté, solo hay un bien infinito, una sabiduría infinita, una armonía y un amor infinitos');
INSERT INTO "negocio" VALUES (58,'Mi alegría me permite expresar mis talentos y habilidades, y estoy agradecida por este empleo');
INSERT INTO "negocio" VALUES (59,'En mi trabajo, mis compañeros de trabajo y yo fomentamos el crecimiento y el éxito de los demás');
INSERT INTO "negocio" VALUES (60,'Cuando me despierto por la mañana, planeo un buen día');
INSERT INTO "negocio" VALUES (61,'Realmente creo que nosotros estamos aquí para bendecirnos el uno al otro');
INSERT INTO "negocio" VALUES (62,'Mi anticipación atrae experiencias positivas');
INSERT INTO "negocio" VALUES (63,'Reflejo esta creencia en mis interacciones diarias');
INSERT INTO "negocio" VALUES (64,'Tengo confianza en mí mismo');
INSERT INTO "negocio" VALUES (65,'Me doy cuenta de que hay leyes que gobiernan el universo y yo trabajo con estas leyes en todos los ámbitos de mi vida');
INSERT INTO "negocio" VALUES (66,'Me siento cómodo hablando en presencia de compañeros de trabajo');
INSERT INTO "negocio" VALUES (67,'Mi anticipación atrae experiencias positivas');
INSERT INTO "negocio" VALUES (68,'Reflejo esta creencia en mis interacciones diarias');
INSERT INTO "salud" VALUES (1,'Cada célula de mi cuerpo vibra con energía saludable.');
INSERT INTO "salud" VALUES (2,'Disfruto de plena salud y altas dosis de energía.');
INSERT INTO "salud" VALUES (3,'Mi cuerpo tiene el poder de sanarse solo.');
INSERT INTO "salud" VALUES (4,'Practico hábitos maravillosos y útiles para mi salud.');
INSERT INTO "salud" VALUES (5,'Confío en que la vida siempre me apoya.');
INSERT INTO "salud" VALUES (6,'Elijo disfrutar y saborear cada minuto de mi día.');
INSERT INTO "salud" VALUES (7,'Cada célula de mi cuerpo está sana y llena de amor.');
INSERT INTO "salud" VALUES (8,'Disfruto de excelente salud y vivo lleno de energía.');
INSERT INTO "salud" VALUES (9,'Todos los días me pongo y me siento más saludable.');
INSERT INTO "salud" VALUES (10,'Me libero del pasado y vivo en el presente.');
INSERT INTO "salud" VALUES (11,'Mi cuerpo se comunica conmigo y yo lo escucho.');
INSERT INTO "salud" VALUES (12,'Mi sistema inmunológico se fortalece cada día.');
INSERT INTO "salud" VALUES (13,'Estoy alineada con el universo.');
INSERT INTO "salud" VALUES (14,'Gozo de una salud perfecta.');
INSERT INTO "salud" VALUES (15,'Atraigo a mi vida todo lo que requiero para mantenerme sana.');
INSERT INTO "salud" VALUES (16,'Agradezco el privilegio de vivir en mi cuerpo.');
INSERT INTO "salud" VALUES (17,'El amor me rodea y protege mi cuerpo.');
INSERT INTO "salud" VALUES (18,'Libero y dejo ir a todos los modelos mentales que me generan malestar.');
INSERT INTO "salud" VALUES (19,'Realizo ejercicios físicos con entusiasmo.');
INSERT INTO "salud" VALUES (20,'Acepto la perfecta salud como el estado natural de mi ser.');
INSERT INTO "salud" VALUES (21,'Cada célula de mi cuerpo funciona perfectamente.');
INSERT INTO "salud" VALUES (22,'Mi mente, cuerpo, emociones y espíritu están en equilibrio.');
INSERT INTO "salud" VALUES (23,'Soy un ser espiritual que está divinamente guiado.');
INSERT INTO "salud" VALUES (24,'Estimulo mi sistema inmunológico con una dieta balanceada.');
INSERT INTO "salud" VALUES (25,'Me enfoco en pensamientos que me nutren y mantienen alta mi vibración.');
INSERT INTO "salud" VALUES (26,'Afecto la perfecta salud como el estado natural de mi ser.');
INSERT INTO "salud" VALUES (27,'Tengo una salud integral maravillosa, me siento fuerte y llena de vida.');
INSERT INTO "salud" VALUES (28,'Estoy dispuesta a dormir lo suficiente para amanecer llena de energía.');
INSERT INTO "salud" VALUES (29,'La gracia y el amor de Dios trabajan a través de mí.');
INSERT INTO "salud" VALUES (30,'Mi cuerpo funciona de la mejor manera todo el tiempo.');
INSERT INTO "salud" VALUES (31,'Me siento fuerte y con gran energía.');
INSERT INTO "salud" VALUES (32,'Mi salud es uno de los grandes tesoros de mi vida.');
INSERT INTO "salud" VALUES (33,'Mi cuerpo es saludable, fuerte y flexible.');
INSERT INTO "salud" VALUES (34,'Presto atención a mi cuerpo todos los días.');
INSERT INTO "salud" VALUES (35,'Tengo un cuerpo rebosante de salud y vida.');
INSERT INTO "salud" VALUES (36,'La luz de Cristo penetra ahora en cada célula de mi cuerpo, doy las gracias por mi salud radiante');
INSERT INTO "salud" VALUES (37,'Soy una persona saludable');
INSERT INTO "salud" VALUES (38,'Mi cuerpo está trabajando para mantenerme saludable y fuerte');
INSERT INTO "salud" VALUES (39,'Me encanta cuidar de mi cuerpo y de mi salud');
INSERT INTO "salud" VALUES (40,'Me demuestro amor propio a través de los alimentos que consumo y las cosas que pienso');
INSERT INTO "salud" VALUES (41,'Cada uno de mis órganos es un motor lleno de vitalidad');
INSERT INTO "salud" VALUES (42,'Estoy llena/o de energía y de vitalidad');
INSERT INTO "salud" VALUES (43,'Hago ejercicios porque amo mi cuerpo y porque celebro todas las cosas que mi cuerpo hace por mí');
INSERT INTO "salud" VALUES (44,'Sé que cualquier molestia física es pasajera, todo está volviendo a la normalidad en este instante');
INSERT INTO "salud" VALUES (45,'Escucho atentamente a mi cuerpo, escucho sus necesidades y las cosas que quiere');
INSERT INTO "salud" VALUES (46,'Me preocupo cada día por aprender hábitos saludables');
INSERT INTO "salud" VALUES (47,'Paso tiempo con gente positiva y saludable');
INSERT INTO "salud" VALUES (48,'Tengo la fortaleza para enfrentar cualquier situación difícil y cambiar su rumbo');
INSERT INTO "salud" VALUES (49,'Mi salud es extraordinaria, perfecta, no tengo nada por lo cual quejarme');
INSERT INTO "salud" VALUES (50,'Mi cuerpo es mi templo, por lo que siempre lo cuido y lo mantengo en forma');
INSERT INTO "salud" VALUES (51,'Cada inhalación me llena de luz y energía');
INSERT INTO "salud" VALUES (52,'Yo soy vida');
INSERT INTO "salud" VALUES (53,'Mi alma se encuentra alojada en un cuerpo perfecto');
INSERT INTO "salud" VALUES (54,'El amor que está en mi corazón fluye por todo mi cuerpo y me hace cada vez más sano');
INSERT INTO "salud" VALUES (55,'La perfecta relación cuerpo-mente-alma sana todo mi ser');
INSERT INTO "salud" VALUES (56,'Me rodeo de la gente que me hace sentir bien');
INSERT INTO "salud" VALUES (57,'Tengo una salud envidiable, en mi mente predominan pensamientos de amor, amor hacia mi cuerpo');
INSERT INTO "salud" VALUES (58,'A partir de este momento quedo libre de todo mal ocasionado por la enfermedad y recupero la fortaleza que hay en mi interior, por que estoy seguro de que este es el anhelo del Universo');
INSERT INTO "salud" VALUES (59,'Mi cuerpo es saludable');
INSERT INTO "salud" VALUES (60,'Mis células, órganos y sistemas funcionan correctamente, permitiéndome tener un cuerpo sano y lleno de energía');
INSERT INTO "salud" VALUES (61,'Mi prioridad en la vida es mantenerme sana');
INSERT INTO "salud" VALUES (62,'Amo cada una de las partículas que conforman mi organismo');
INSERT INTO "salud" VALUES (63,'A diario, agradezco por la excelente salud que tengo y por el maravilloso funcionamiento de mi cuerpo');
INSERT INTO "salud" VALUES (64,'Estoy libre de las tensiones, me permito ser paciente y me tomo tiempo suficiente para descansar, ya que comprendo que ésta es la forma para liberar al cuerpo de la tensión');
INSERT INTO "salud" VALUES (65,'La actividad física me permite despejar mi mente y expulsar por mis poros todas aquellas toxinas que se encuentran en mi cuerpo');
INSERT INTO "salud" VALUES (66,'Mi cuerpo está sanando y me siento mejor cada día');
INSERT INTO "salud" VALUES (67,'Soy una persona saludable');
INSERT INTO "salud" VALUES (68,'Mi cuerpo está trabajando para mantenerme saludable y fuerte');
INSERT INTO "salud" VALUES (69,'Me encanta cuidar de mi cuerpo y de mi salud');
INSERT INTO "salud" VALUES (70,'Me demuestro amor propio a través de los alimentos que consumo y las cosas que pienso');
INSERT INTO "salud" VALUES (71,'Cada uno de mis órganos es un motor lleno de vitalidad');
INSERT INTO "salud" VALUES (72,'Estoy llena/o de energía y de vitalidad');
INSERT INTO "salud" VALUES (73,'Hago ejercicios porque amo mi cuerpo y porque celebro todas las cosas que mi cuerpo hace por mí');
INSERT INTO "salud" VALUES (74,'Sé que cualquier molestia física es pasajera, todo está volviendo a la normalidad en este instante');
INSERT INTO "salud" VALUES (75,'Escucho atentamente a mi cuerpo, escucho sus necesidades y las cosas que quiere');
INSERT INTO "salud" VALUES (76,'Me preocupo cada día por aprender hábitos saludables');
INSERT INTO "salud" VALUES (77,'Mi alma está tranquila');
COMMIT;
